// packages/examples/svelte/src/demos/aggregate-functions/AggregateFunctionsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { aggregateFunctionsConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={aggregateFunctionsConfig.headers}
  rows={aggregateFunctionsConfig.rows}
  rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
  columnResizing={aggregateFunctionsConfig.tableProps.columnResizing}
  {height}
  {theme}
/>

// packages/examples/solid/src/demos/aggregate-functions/AggregateFunctionsDemo.tsx
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { aggregateFunctionsConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

export default function AggregateFunctionsDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={aggregateFunctionsConfig.headers}
      rows={aggregateFunctionsConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
