// solid/cell-clicking/src/demos/cell-clicking/CellClickingDemo.tsx
import { createSignal, createMemo, Show, For } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, SolidColumnDef, CellRendererProps, CellClickProps } from "@simple-table/solid";
import { cellClickingHeaders, cellClickingData, CELL_CLICKING_STATUSES } from "./cell-clicking.demo-data";
import type { ProjectTask } from "./cell-clicking.demo-data";
import "@simple-table/solid/styles.css";

const DETAIL_KEYS = ["task", "details", "assignee", "status", "priority"] as const;

export default function CellClickingDemo(props: { height?: string | number; theme?: Theme }) {
  const [clickInfo, setClickInfo] = createSignal("");
  const [selectedTask, setSelectedTask] = createSignal<ProjectTask | null>(null);
  const [rows, setRows] = createSignal<ProjectTask[]>([...cellClickingData]);

  const headers: SolidColumnDef<ProjectTask>[] = cellClickingHeaders.map((h) => {
    if (h.accessor === "priority") {
      return {
        ...h,
        cellRenderer: (cr: CellRendererProps<ProjectTask>) => {
          const p = String(cr.row.priority);
          const color = p === "High" ? "#ef4444" : p === "Medium" ? "#f59e0b" : "#10b981";
          return (
            <span style={{ color, "font-weight": "bold", cursor: "pointer" }} title="Click to filter">
              {p}
            </span>
          );
        },
      };
    }
    if (h.accessor === "status") {
      return {
        ...h,
        cellRenderer: (cr: CellRendererProps<ProjectTask>) => {
          const s = String(cr.row.status);
          const bg = s === "Completed" ? "#dcfce7" : s === "In Progress" ? "#fef3c7" : "#fee2e2";
          const c = s === "Completed" ? "#166534" : s === "In Progress" ? "#92400e" : "#991b1b";
          return (
            <span
              style={{
                background: bg,
                color: c,
                padding: "4px 8px",
                "border-radius": "4px",
                "font-size": "12px",
                "font-weight": "bold",
                cursor: "pointer",
              }}
              title="Click to change"
            >
              {s}
            </span>
          );
        },
      };
    }
    if (h.accessor === "details") {
      return {
        ...h,
        cellRenderer: () => (
          <button
            type="button"
            style={{
              background: "#3b82f6",
              color: "white",
              border: "none",
              padding: "6px 12px",
              "border-radius": "4px",
              cursor: "pointer",
              "font-size": "12px",
              "font-weight": "bold",
            }}
          >
            View Details
          </button>
        ),
      };
    }
    return h;
  });

  const isDark = createMemo(() => props.theme === "modern-dark" || props.theme === "dark" || props.theme === "modern-black");

  const handleCellClick = ({ accessor, rowIndex, value, row }: CellClickProps<ProjectTask>) => {
    const task = row;
    switch (accessor) {
      case "priority":
        setClickInfo(`Filtering by ${value} priority`);
        setRows(cellClickingData.filter((t) => t.priority === value));
        break;
      case "status": {
        const idx = CELL_CLICKING_STATUSES.indexOf(String(value));
        const next = CELL_CLICKING_STATUSES[(idx + 1) % CELL_CLICKING_STATUSES.length];
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, status: next } : t)));
        setClickInfo(`Status: "${value}" → "${next}"`);
        break;
      }
      case "details":
        setSelectedTask(task);
        setClickInfo(`Opening details for: ${task.task}`);
        break;
      case "estimatedHours": {
        const n = Math.min(task.estimatedHours + 2, 40);
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, estimatedHours: n } : t)));
        setClickInfo(`Est. hours: ${task.estimatedHours}h → ${n}h`);
        break;
      }
      case "completedHours": {
        const n = Math.min(task.completedHours + 1, task.estimatedHours);
        setRows((prev) => prev.map((t) => (t.id === task.id ? { ...t, completedHours: n } : t)));
        setClickInfo(`Done hours: ${task.completedHours}h → ${n}h`);
        break;
      }
      default:
        setClickInfo(`Clicked [${accessor}] = "${value}" (row ${rowIndex})`);
    }
  };

  return (
    <div style={{ display: "flex", "flex-direction": "column", gap: "16px" }}>
      <div
        style={{
          padding: "12px",
          "background-color": isDark() ? "#374151" : "#f3f4f6",
          "border-radius": "8px",
          border: `1px solid ${isDark() ? "#4b5563" : "#d1d5db"}`,
          "min-height": "48px",
          display: "flex",
          "align-items": "center",
        }}
      >
        <strong style={{ "margin-right": "8px", color: isDark() ? "#f9fafb" : "#1f2937" }}>Last Click:</strong>
        <span style={{ color: isDark() ? "#d1d5db" : "#4b5563" }}>
          {clickInfo() || "Click any cell to see interaction details..."}
        </span>
      </div>

      <Show when={selectedTask()}>
        {(task) => (
          <div
            style={{
              position: "fixed",
              inset: "0",
              background: "rgba(0,0,0,0.5)",
              display: "flex",
              "align-items": "center",
              "justify-content": "center",
              "z-index": 1000,
            }}
          >
            <div
              style={{
                background: isDark() ? "#1f2937" : "white",
                padding: "24px",
                "border-radius": "8px",
                "max-width": "500px",
                width: "90%",
              }}
            >
              <h3 style={{ margin: "0 0 16px", color: isDark() ? "#f9fafb" : "#1f2937" }}>Task Details</h3>
              <For each={DETAIL_KEYS}>
                {(key) => (
                  <p style={{ margin: "8px 0", color: isDark() ? "#d1d5db" : "#4b5563" }}>
                    <strong>{key.charAt(0).toUpperCase() + key.slice(1)}:</strong> {String(task()[key])}
                  </p>
                )}
              </For>
              <button
                type="button"
                onClick={() => setSelectedTask(null)}
                style={{
                  "margin-top": "16px",
                  background: "#3b82f6",
                  color: "white",
                  border: "none",
                  padding: "8px 16px",
                  "border-radius": "4px",
                  cursor: "pointer",
                  "font-weight": "bold",
                }}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </Show>

      <SimpleTable
        columnResizing
        columns={headers}
        getRowId={({ row }) => row.id}
        height={props.height ?? "320px"}
        onCellClick={handleCellClick}
        rows={rows()}
        theme={props.theme}
      />
    </div>
  );
}

// vue/cell-clicking/src/demos/cell-clicking/CellClickingDemo.vue
<script setup lang="ts">
import { ref, computed, h } from "vue";
import { SimpleTable } from "@simple-table/vue";
import type { Theme, VueColumnDef, CellClickProps, CellRendererProps, GetRowIdParams } from "@simple-table/vue";
import { cellClickingHeaders, cellClickingData, CELL_CLICKING_STATUSES } from "./cell-clicking.demo-data";
import type { ProjectTask } from "./cell-clicking.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "320px",
});

const clickInfo = ref("");
const selectedTask = ref<ProjectTask | null>(null);
const rows = ref<ProjectTask[]>([...cellClickingData]);

const headers: VueColumnDef<ProjectTask>[] = cellClickingHeaders.map((col) => {
  if (col.accessor === "priority") {
    return {
      ...col,
      cellRenderer: ({ row }: CellRendererProps<ProjectTask>) => {
        const p = row.priority;
        const color = p === "High" ? "#ef4444" : p === "Medium" ? "#f59e0b" : "#10b981";
        return h(
          "span",
          {
            style: { color, fontWeight: "bold", cursor: "pointer" },
            title: "Click to filter by priority",
          },
          p,
        );
      },
    };
  }
  if (col.accessor === "status") {
    return {
      ...col,
      cellRenderer: ({ row }: CellRendererProps<ProjectTask>) => {
        const s = row.status;
        const bg = s === "Completed" ? "#dcfce7" : s === "In Progress" ? "#fef3c7" : "#fee2e2";
        const color = s === "Completed" ? "#166534" : s === "In Progress" ? "#92400e" : "#991b1b";
        return h(
          "span",
          {
            style: {
              backgroundColor: bg,
              color,
              padding: "4px 8px",
              borderRadius: "4px",
              fontSize: "12px",
              fontWeight: "bold",
              cursor: "pointer",
            },
            title: "Click to change status",
          },
          s,
        );
      },
    };
  }
  if (col.accessor === "details") {
    return {
      ...col,
      cellRenderer: () =>
        h(
          "button",
          {
            style: {
              background: "#3b82f6",
              color: "white",
              border: "none",
              padding: "6px 12px",
              borderRadius: "4px",
              cursor: "pointer",
              fontSize: "12px",
              fontWeight: "bold",
            },
            title: "Click to view task details",
          },
          "View Details",
        ),
    };
  }
  return { ...col };
});

const isDark = computed(() => props.theme === "modern-dark" || props.theme === "dark" || props.theme === "modern-black");

const getRowId = ({ row }: GetRowIdParams<ProjectTask>) => row.id;

function handleCellClick({ accessor, rowIndex, value, row }: CellClickProps<ProjectTask>) {
  switch (accessor) {
    case "priority":
      clickInfo.value = `Filtering by ${value} priority`;
      rows.value = cellClickingData.filter((t) => t.priority === value);
      break;
    case "status": {
      const idx = CELL_CLICKING_STATUSES.indexOf(String(value));
      const next = CELL_CLICKING_STATUSES[(idx + 1) % CELL_CLICKING_STATUSES.length];
      rows.value = rows.value.map((t) => (t.id === row.id ? { ...t, status: next } : t));
      clickInfo.value = `Status: "${value}" → "${next}"`;
      break;
    }
    case "details":
      selectedTask.value = row;
      clickInfo.value = `Opening details for: ${row.task}`;
      break;
    case "estimatedHours": {
      const n = Math.min(row.estimatedHours + 2, 40);
      rows.value = rows.value.map((t) => (t.id === row.id ? { ...t, estimatedHours: n } : t));
      clickInfo.value = `Est. hours: ${row.estimatedHours}h → ${n}h`;
      break;
    }
    case "completedHours": {
      const n = Math.min(row.completedHours + 1, row.estimatedHours);
      rows.value = rows.value.map((t) => (t.id === row.id ? { ...t, completedHours: n } : t));
      clickInfo.value = `Done hours: ${row.completedHours}h → ${n}h`;
      break;
    }
    default:
      clickInfo.value = `Clicked [${accessor}] = "${value}" (row ${rowIndex})`;
  }
}
</script>

<template>
  <div style="display: flex; flex-direction: column; gap: 16px">
    <div
      :style="{
        padding: '12px',
        backgroundColor: isDark ? '#374151' : '#f3f4f6',
        borderRadius: '8px',
        border: '1px solid ' + (isDark ? '#4b5563' : '#d1d5db'),
        minHeight: '48px',
        display: 'flex',
        alignItems: 'center',
      }"
    >
      <strong :style="{ marginRight: '8px', color: isDark ? '#f9fafb' : '#1f2937' }">Last Click:</strong>
      <span :style="{ color: isDark ? '#d1d5db' : '#4b5563' }">
        {{ clickInfo || "Click any cell to see interaction details..." }}
      </span>
    </div>

    <div
      v-if="selectedTask"
      style="position: fixed; inset: 0; background: rgba(0,0,0,0.5); display: flex; align-items: center; justify-content: center; z-index: 1000"
    >
      <div
        :style="{ background: isDark ? '#1f2937' : 'white', padding: '24px', borderRadius: '8px', maxWidth: '500px', width: '90%' }"
      >
        <h3 :style="{ margin: '0 0 16px', color: isDark ? '#f9fafb' : '#1f2937' }">Task Details</h3>
        <p :style="{ margin: '8px 0', color: isDark ? '#d1d5db' : '#4b5563' }"><strong>Task:</strong> {{ selectedTask.task }}</p>
        <p :style="{ margin: '8px 0', color: isDark ? '#d1d5db' : '#4b5563' }"><strong>Details:</strong> {{ selectedTask.details }}</p>
        <p :style="{ margin: '8px 0', color: isDark ? '#d1d5db' : '#4b5563' }"><strong>Assignee:</strong> {{ selectedTask.assignee }}</p>
        <p :style="{ margin: '8px 0', color: isDark ? '#d1d5db' : '#4b5563' }"><strong>Status:</strong> {{ selectedTask.status }}</p>
        <p :style="{ margin: '8px 0', color: isDark ? '#d1d5db' : '#4b5563' }"><strong>Priority:</strong> {{ selectedTask.priority }}</p>
        <button
          @click="selectedTask = null"
          style="margin-top: 16px; background: #3b82f6; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-weight: bold"
        >
          Close
        </button>
      </div>
    </div>

    <SimpleTable
      :column-resizing="true"
      :columns="headers"
      :get-row-id="getRowId"
      :height="height"
      :on-cell-click="handleCellClick"
      :rows="rows"
      :theme="theme"
    />
  </div>
</template>
