// svelte/billing/src/demos/billing/BillingNameCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { BillingRow } from "./billing.demo-data";

  let { row }: CellRendererProps<BillingRow> = $props();
</script>

{#if row.type === "account"}
  <span style="font-weight: 600">{row.name}</span>
{:else}
  {row.name}
{/if}

// packages/examples/angular/src/demos/billing/billing-name-cell.component.ts
import { Component, Input } from "@angular/core";
import type {  } from "@simple-table/angular";
import type { BillingRow } from "./billing.demo-data";

@Component({
  standalone: true,
  selector: "demo-billing-name-cell",
  template: `
    @if (isAccount) {
      <span style="font-weight:600;">{{ name }}</span>
    } @else {
      {{ name }}
    }
  `,
})
export class BillingNameCellComponent {
  @Input({ required: true }) row!: BillingRow;

  get isAccount(): boolean {
    return this.row.type === "account";
  }

  get name(): string {
    return this.row.name;
  }
}
