// packages/examples/solid/src/demos/column-selection/ColumnSelectionDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { columnSelectionConfig } from "./column-selection.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnSelectionDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(columnSelectionConfig.headers)}
      rows={columnSelectionConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      selectableColumns={columnSelectionConfig.tableProps.selectableColumns}
    />
  );
}

// packages/examples/svelte/src/demos/column-selection/ColumnSelectionDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { columnSelectionConfig } from "./column-selection.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(columnSelectionConfig.headers)}
  rows={columnSelectionConfig.rows}
  {height}
  {theme}
  selectableColumns={columnSelectionConfig.tableProps.selectableColumns}
/>
