// packages/examples/react/src/demos/column-selection/ColumnSelectionDemo.tsx
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { columnSelectionConfig } from "./column-selection.demo-data";
import "@simple-table/react/styles.css";

const ColumnSelectionDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(columnSelectionConfig.headers)}
      rows={columnSelectionConfig.rows}
      height={height}
      theme={theme}
      selectableColumns={columnSelectionConfig.tableProps.selectableColumns}
    />
  );
};

export default ColumnSelectionDemo;

// packages/examples/svelte/src/demos/column-selection/ColumnSelectionDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { columnSelectionConfig } from "./column-selection.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(columnSelectionConfig.headers)}
  rows={columnSelectionConfig.rows}
  {height}
  {theme}
  selectableColumns={columnSelectionConfig.tableProps.selectableColumns}
/>
