// svelte/charts/src/demos/charts/ChartsDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { chartsConfig } from "./charts.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columnReordering={chartsConfig.tableProps.columnReordering}
  columnResizing={chartsConfig.tableProps.columnResizing}
  columns={chartsConfig.headers}
  rows={chartsConfig.rows}
  selectableCells={chartsConfig.tableProps.selectableCells}
  {height}
  {theme}
/>

// packages/examples/react/src/demos/charts/ChartsDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { chartsConfig } from "./charts.demo-data";
import "@simple-table/react/styles.css";

const ChartsDemo = ({ height = "400px", theme }: { height?: string | number; theme?: Theme }) => {
  return (
    <SimpleTable
      columnReordering={chartsConfig.tableProps.columnReordering}
      columnResizing={chartsConfig.tableProps.columnResizing}
      columns={chartsConfig.headers}
      rows={chartsConfig.rows}
      selectableCells={chartsConfig.tableProps.selectableCells}
      height={height}
      theme={theme}
    />
  );
};

export default ChartsDemo;
