// svelte/nested-headers/src/demos/nested-headers/NestedHeadersDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { nestedHeadersConfig } from "./nested-headers.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={nestedHeadersConfig.headers}
  rows={nestedHeadersConfig.rows}
  {height}
  {theme}
  columnResizing={nestedHeadersConfig.tableProps.columnResizing}
/>

// react/nested-headers/src/demos/nested-headers/NestedHeadersDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { nestedHeadersConfig } from "./nested-headers.demo-data";
import "@simple-table/react/styles.css";

const NestedHeadersDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      columns={nestedHeadersConfig.headers}
      rows={nestedHeadersConfig.rows}
      height={height}
      theme={theme}
      columnResizing={nestedHeadersConfig.tableProps.columnResizing}
    />
  );
};

export default NestedHeadersDemo;
