// solid/column-editing/src/demos/column-editing/ColumnEditingDemo.tsx
import { createSignal, createMemo } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, SolidColumnDef } from "@simple-table/solid";
import {
  columnEditingData,
  columnEditingHeaders,
  type ColumnEditingEmployee,
} from "./column-editing.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnEditingDemo(props: { height?: string | number; theme?: Theme }) {
  const [additionalColumns, setAdditionalColumns] = createSignal<
    SolidColumnDef<ColumnEditingEmployee>[]
  >([]);
  const [lastAdded, setLastAdded] = createSignal("");

  const addColumn = () => {
    const n = additionalColumns().length + 1;
    const col: SolidColumnDef<ColumnEditingEmployee> = {
      accessor: `custom-${n}`,
      label: `Custom ${n}`,
      width: 120,
      type: "string",
    };
    setAdditionalColumns([...additionalColumns(), col]);
    setLastAdded(col.label);
  };

  const headers = createMemo(() => [...columnEditingHeaders, ...additionalColumns()]);

  return (
    <div>
      <div style={{ "margin-bottom": "12px" }}>
        <button
          type="button"
          onClick={addColumn}
          style={{
            "background-color": "#007bff",
            color: "white",
            border: "none",
            padding: "6px 14px",
            "border-radius": "4px",
            cursor: "pointer",
            "font-size": "13px",
          }}
        >
          + Add Column
        </button>
        {lastAdded() && (
          <span style={{ "margin-left": "12px", color: "#64748b", "font-size": "13px" }}>Added: {lastAdded()}</span>
        )}
      </div>
      <SimpleTable
        columns={headers()}
        getRowId={({ row }) => row.id}
        rows={columnEditingData}
        height={props.height ?? "400px"}
        theme={props.theme}
        enableHeaderEditing
        selectableColumns
        onHeaderEdit={(_header: SolidColumnDef<ColumnEditingEmployee>, newLabel: string) =>
          setLastAdded(`Renamed to: ${newLabel}`)
        }
      />
    </div>
  );
}

// packages/examples/react/src/demos/column-editing/ColumnEditingDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactColumnDef } from "@simple-table/react";
import {
  columnEditingData,
  columnEditingHeaders,
  type ColumnEditingEmployee,
} from "./column-editing.demo-data";
import "@simple-table/react/styles.css";

const ColumnEditingDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [additionalColumns, setAdditionalColumns] = useState<
    ReactColumnDef<ColumnEditingEmployee>[]
  >([]);
  const [lastAdded, setLastAdded] = useState("");

  const headers: ReactColumnDef<ColumnEditingEmployee>[] = useMemo(
    () => [...columnEditingHeaders, ...additionalColumns],
    [additionalColumns],
  );

  const addColumn = () => {
    const n = additionalColumns.length + 1;
    const col: ReactColumnDef<ColumnEditingEmployee> = {
      accessor: `custom-${n}`,
      label: `Custom ${n}`,
      width: 120,
      type: "string",
    };
    setAdditionalColumns((prev) => [...prev, col]);
    setLastAdded(col.label);
  };

  const handleHeaderEdit = (_header: ReactColumnDef<ColumnEditingEmployee>, newLabel: string) => {
    setLastAdded(`Renamed to: ${newLabel}`);
  };

  return (
    <div>
      <div style={{ marginBottom: 12 }}>
        <button
          onClick={addColumn}
          style={{
            backgroundColor: "#007bff",
            color: "white",
            border: "none",
            padding: "6px 14px",
            borderRadius: "4px",
            cursor: "pointer",
            fontSize: "13px",
          }}
        >
          + Add Column
        </button>
        {lastAdded && (
          <span style={{ marginLeft: 12, color: "#64748b", fontSize: 13 }}>Added: {lastAdded}</span>
        )}
      </div>
      <SimpleTable<ColumnEditingEmployee>
        columns={headers}
        getRowId={({ row }) => row.id}
        rows={columnEditingData}
        enableHeaderEditing
        selectableColumns
        onHeaderEdit={handleHeaderEdit}
        height={height}
        theme={theme}
      />
    </div>
  );
};

export default ColumnEditingDemo;
