// svelte/nested-tables/src/demos/nested-tables/NestedTablesDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "500px", theme }: { height?: string | number; theme?: Theme } = $props();

  const sampleData = generateNestedTablesData(25);
</script>

<SimpleTable
  autoExpandColumns={nestedTablesConfig.tableProps.autoExpandColumns}
  columns={nestedTablesConfig.headers}
  rows={sampleData}
  rowGrouping={nestedTablesConfig.tableProps.rowGrouping}
  getRowId={nestedTablesConfig.tableProps.getRowId}
  expandAll={nestedTablesConfig.tableProps.expandAll}
  columnResizing={nestedTablesConfig.tableProps.columnResizing}
  {height}
  {theme}
/>

// packages/examples/react/src/demos/nested-tables/NestedTablesDemo.tsx
import { useMemo } from "react";
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
import "@simple-table/react/styles.css";

const NestedTablesDemo = ({ height = "500px", theme }: { height?: string | number; theme?: Theme }) => {
  const sampleData = useMemo(() => generateNestedTablesData(25), []);

  return (
    <SimpleTable
      autoExpandColumns={nestedTablesConfig.tableProps.autoExpandColumns}
      columns={nestedTablesConfig.headers}
      rows={sampleData}
      rowGrouping={nestedTablesConfig.tableProps.rowGrouping}
      getRowId={nestedTablesConfig.tableProps.getRowId}
      expandAll={nestedTablesConfig.tableProps.expandAll}
      columnResizing={nestedTablesConfig.tableProps.columnResizing}
      height={height}
      theme={theme}
    />
  );
};

export default NestedTablesDemo;
