// packages/examples/react/src/demos/column-width/ColumnWidthDemo.tsx
import { useState, useEffect } from "react";
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { columnWidthConfig } from "./column-width.demo-data";
import "@simple-table/react/styles.css";

const ColumnWidthDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 768);
    check();
    window.addEventListener("resize", check);
    return () => window.removeEventListener("resize", check);
  }, []);

  return (
    <SimpleTable
      autoExpandColumns={!isMobile}
      columnResizing
      defaultHeaders={defaultHeadersFromCore(columnWidthConfig.headers)}
      height={height}
      rows={columnWidthConfig.rows}
      theme={theme}
    />
  );
};

export default ColumnWidthDemo;

// packages/examples/svelte/src/demos/column-width/ColumnWidthDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { columnWidthConfig } from "./column-width.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let isMobile = $state(false);

  function checkMobile() {
    isMobile = window.innerWidth < 768;
  }

  $effect(() => {
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  });
</script>

<SimpleTable
  autoExpandColumns={!isMobile}
  columnResizing={true}
  defaultHeaders={defaultHeadersFromCore(columnWidthConfig.headers)}
  rows={columnWidthConfig.rows}
  {height}
  {theme}
/>
