// packages/examples/solid/src/demos/dynamic-row-loading/DynamicRowLoadingDemo.tsx
import { createSignal } from "solid-js";
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme, OnRowGroupExpandProps } from "@simple-table/solid";
import {
  dynamicRowLoadingConfig,
  generateInitialRegions,
  fetchStoresForRegion,
  fetchProductsForStore,
} from "./dynamic-row-loading.demo-data";
import type { DynamicRegion, DynamicStore } from "./dynamic-row-loading.demo-data";
import "@simple-table/solid/styles.css";

export default function DynamicRowLoadingDemo(props: { height?: string | number; theme?: Theme }) {
  const [rows, setRows] = createSignal<DynamicRegion[]>(generateInitialRegions());

  const handleRowExpand = async ({
    row,
    depth,
    groupingKey,
    isExpanded,
    setLoading,
    setError,
    setEmpty,
    rowIndexPath,
  }: OnRowGroupExpandProps) => {
    if (!isExpanded) return;
    if (groupingKey && row[groupingKey] && (row[groupingKey] as unknown[]).length > 0) return;

    try {
      if (depth === 0 && groupingKey === "stores") {
        setLoading(true);
        const stores = await fetchStoresForRegion((row as DynamicRegion).id);
        setLoading(false);
        if (stores.length === 0) {
          setEmpty(true, "No stores found");
          return;
        }
        setRows((prev) => {
          const newRows = [...prev];
          newRows[rowIndexPath[0]].stores = stores;
          return newRows;
        });
      } else if (depth === 1 && groupingKey === "products") {
        setLoading(true);
        const products = await fetchProductsForStore((row as DynamicStore).id);
        setLoading(false);
        if (products.length === 0) {
          setEmpty(true, "No products found");
          return;
        }
        setRows((prev) => {
          const newRows = [...prev];
          const region = newRows[rowIndexPath[0]];
          if (region.stores && region.stores[rowIndexPath[1]]) {
            region.stores[rowIndexPath[1]].products = products;
          }
          return newRows;
        });
      }
    } catch (error) {
      setLoading(false);
      setError(error instanceof Error ? error.message : "Failed to load data");
    }
  };

  return (
    <SimpleTable
      columnResizing={dynamicRowLoadingConfig.tableProps.columnResizing}
      defaultHeaders={defaultHeadersFromCore(dynamicRowLoadingConfig.headers)}
      editColumns={dynamicRowLoadingConfig.tableProps.editColumns}
      expandAll={dynamicRowLoadingConfig.tableProps.expandAll}
      height={props.height ?? "400px"}
      onRowGroupExpand={handleRowExpand}
      rowGrouping={dynamicRowLoadingConfig.tableProps.rowGrouping}
      getRowId={dynamicRowLoadingConfig.tableProps.getRowId}
      rows={rows()}
      selectableCells={dynamicRowLoadingConfig.tableProps.selectableCells}
      theme={props.theme}
      useOddEvenRowBackground={dynamicRowLoadingConfig.tableProps.useOddEvenRowBackground}
    />
  );
}

// svelte/dynamic-row-loading/src/demos/dynamic-row-loading/DynamicRowLoadingDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme, OnRowGroupExpandProps } from "@simple-table/svelte";
  import {
    dynamicRowLoadingConfig,
    generateInitialRegions,
    fetchStoresForRegion,
    fetchProductsForStore,
  } from "./dynamic-row-loading.demo-data";
  import type { DynamicRegion, DynamicStore } from "./dynamic-row-loading.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let rows = $state<DynamicRegion[]>(generateInitialRegions());

  async function handleRowExpand({
    row,
    depth,
    groupingKey,
    isExpanded,
    setLoading,
    setError,
    setEmpty,
    rowIndexPath,
  }: OnRowGroupExpandProps) {
    if (!isExpanded) return;
    if (groupingKey && row[groupingKey] && (row[groupingKey] as unknown[]).length > 0) return;

    try {
      if (depth === 0 && groupingKey === "stores") {
        setLoading(true);
        const stores = await fetchStoresForRegion((row as DynamicRegion).id);
        setLoading(false);
        if (stores.length === 0) {
          setEmpty(true, "No stores found");
          return;
        }
        const newRows = [...rows];
        newRows[rowIndexPath[0]].stores = stores;
        rows = newRows;
      } else if (depth === 1 && groupingKey === "products") {
        setLoading(true);
        const products = await fetchProductsForStore((row as DynamicStore).id);
        setLoading(false);
        if (products.length === 0) {
          setEmpty(true, "No products found");
          return;
        }
        const newRows = [...rows];
        const region = newRows[rowIndexPath[0]];
        if (region.stores && region.stores[rowIndexPath[1]]) {
          region.stores[rowIndexPath[1]].products = products;
        }
        rows = newRows;
      }
    } catch (error) {
      setLoading(false);
      setError(error instanceof Error ? error.message : "Failed to load data");
    }
  }
</script>

<SimpleTable
  columnResizing={dynamicRowLoadingConfig.tableProps.columnResizing}
  defaultHeaders={defaultHeadersFromCore(dynamicRowLoadingConfig.headers)}
  editColumns={dynamicRowLoadingConfig.tableProps.editColumns}
  expandAll={dynamicRowLoadingConfig.tableProps.expandAll}
  {height}
  onRowGroupExpand={handleRowExpand}
  rowGrouping={dynamicRowLoadingConfig.tableProps.rowGrouping}
  getRowId={dynamicRowLoadingConfig.tableProps.getRowId}
  rows={rows}
  selectableCells={dynamicRowLoadingConfig.tableProps.selectableCells}
  {theme}
  useOddEvenRowBackground={dynamicRowLoadingConfig.tableProps.useOddEvenRowBackground}
/>
