// packages/examples/vue/src/demos/column-visibility/ColumnVisibilityDemo.vue
<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { ColumnVisibilityState, Theme } from "@simple-table/vue";
import MarketingColumnEditorRow from "./MarketingColumnEditorRow.vue";
import {
  columnVisibilityConfig,
  getColumnVisibilityDemoHeaders,
  loadColumnVisibilityDemoSaved,
  saveColumnVisibilityDemoState,
} from "./column-visibility.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const columns = getColumnVisibilityDemoHeaders(loadColumnVisibilityDemoSaved());

const columnEditorConfig = {
  ...columnVisibilityConfig.tableProps.columnEditorConfig,
  rowRenderer: MarketingColumnEditorRow,
};

function onColumnVisibilityChange(state: ColumnVisibilityState) {
  saveColumnVisibilityDemoState(state);
}
</script>

<template>
  <SimpleTable
    :columns="columns"
    :rows="columnVisibilityConfig.rows"
    :enable-column-editor="columnVisibilityConfig.tableProps.enableColumnEditor"
    :enable-column-editor-init-open="columnVisibilityConfig.tableProps.enableColumnEditorInitOpen"
    :column-editor-config="columnEditorConfig"
    :height="props.height"
    :theme="props.theme"
    :on-column-visibility-change="onColumnVisibilityChange"
  />
</template>

// solid/column-visibility/src/demos/column-visibility/ColumnVisibilityDemo.tsx
import {
  SimpleTable,
  type ColumnVisibilityState,
  type Theme,
} from "@simple-table/solid";
import {
  columnVisibilityConfig,
  getColumnVisibilityDemoHeaders,
  loadColumnVisibilityDemoSaved,
  saveColumnVisibilityDemoState,
} from "./column-visibility.demo-data";
import MarketingColumnEditorRow from "./MarketingColumnEditorRow";
import "@simple-table/solid/styles.css";

export default function ColumnVisibilityDemo(props: { height?: string | number; theme?: Theme }) {
  const headers = () => getColumnVisibilityDemoHeaders(loadColumnVisibilityDemoSaved());

  const onColumnVisibilityChange = (state: ColumnVisibilityState) => {
    saveColumnVisibilityDemoState(state);
  };

  return (
    <SimpleTable
      columns={headers()}
      rows={columnVisibilityConfig.rows}
      enableColumnEditor
      enableColumnEditorInitOpen
      height={props.height ?? "400px"}
      theme={props.theme}
      onColumnVisibilityChange={onColumnVisibilityChange}
      columnEditorConfig={{
        ...columnVisibilityConfig.tableProps.columnEditorConfig,
        rowRenderer: MarketingColumnEditorRow,
      }}
    />
  );
}
