// angular/music/src/demos/music/music-ratio-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Theme } from "@simple-table/angular";
import { getMusicThemeColors } from "./music.demo-data";
import type { MusicArtist } from "./music.demo-data";

@Component({
  standalone: true,
  selector: "demo-music-ratio",
  template: `<span [style.color]="c.gray">{{ row.reachFollowersRatio.toFixed(1) }}x</span>`,
})
export class MusicRatioCellComponent {
  @Input({ required: true }) row!: MusicArtist;
  @Input() theme?: Theme;

  get c(): Record<string, string> {
    return getMusicThemeColors(this.theme);
  }
}

// packages/examples/svelte/src/demos/music/MusicRatioCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getMusicThemeColors } from "./music.demo-data";
  import type { MusicArtist } from "./music.demo-data";

  let { row, theme }: CellRendererProps<MusicArtist> = $props();
  const c = $derived(getMusicThemeColors(theme));
</script>

<span style="color:{c.gray};">{row.reachFollowersRatio.toFixed(1)}x</span>
