// packages/examples/angular/src/demos/music/music-artist-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Theme } from "@simple-table/angular";
import { getMusicThemeColors } from "./music.demo-data";
import type { MusicArtist } from "./music.demo-data";
import { MusicTagComponent } from "./music-tag.component";

@Component({
  standalone: true,
  selector: "demo-music-artist",
  imports: [MusicTagComponent],
  template: `
    <div style="display:flex;align-items:center;gap:12px;">
      <div [attr.style]="avatarStyle">{{ initial }}</div>
      <div style="display:flex;flex-direction:column;gap:6px;flex:1;">
        <span style="font-weight:500;font-size:14px;" [style.color]="c.gray">{{ row.artistName }}</span>
        <div style="display:flex;gap:6px;flex-wrap:wrap;">
          <demo-music-tag [text]="d.growthStatus" variant="default" [theme]="theme" />
          <demo-music-tag [text]="d.mood" variant="default" [theme]="theme" />
          <demo-music-tag [text]="d.genre" variant="default" [theme]="theme" />
        </div>
      </div>
    </div>
  `,
})
export class MusicArtistCellComponent {
  @Input({ required: true }) row!: MusicArtist;
  @Input() theme?: Theme;

  get c(): Record<string, string> {
    return getMusicThemeColors(this.theme);
  }

  get initial(): string {
    return this.row.artistName.charAt(0).toUpperCase();
  }

  get avatarStyle(): string {
    let hash = 0;
    const name = this.row.artistName;
    for (let i = 0; i < name.length; i++) {
      hash = name.charCodeAt(i) + ((hash << 5) - hash);
    }
    return `width:40px;height:40px;border-radius:50%;background-color:hsl(${hash % 360}, 65%, 55%);display:flex;align-items:center;justify-content:center;color:white;font-size:16px;flex-shrink:0;`;
  }
}

// svelte/music/src/demos/music/MusicArtistCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getMusicThemeColors } from "./music.demo-data";
  import type { MusicArtist } from "./music.demo-data";
  import MusicTag from "./MusicTag.svelte";

  let { row, theme }: CellRendererProps<MusicArtist> = $props();
  const c = $derived(getMusicThemeColors(theme));

  const avatarStyle = $derived.by(() => {
    let hash = 0;
    for (let i = 0; i < row.artistName.length; i++) {
      hash = row.artistName.charCodeAt(i) + ((hash << 5) - hash);
    }
    return `width:40px;height:40px;border-radius:50%;background-color:hsl(${hash % 360}, 65%, 55%);display:flex;align-items:center;justify-content:center;color:white;font-size:16px;flex-shrink:0;`;
  });
</script>

<div style="display:flex;align-items:center;gap:12px;">
  <div style={avatarStyle}>{row.artistName.charAt(0).toUpperCase()}</div>
  <div style="display:flex;flex-direction:column;gap:6px;flex:1;">
    <span style="font-weight:500;font-size:14px;color:{c.gray};">{row.artistName}</span>
    <div style="display:flex;gap:6px;flex-wrap:wrap;">
      <MusicTag text={row.growthStatus} variant="default" c={c} />
      <MusicTag text={row.mood} variant="default" c={c} />
      <MusicTag text={row.genre} variant="default" c={c} />
    </div>
  </div>
</div>
