// packages/examples/react/src/demos/tooltip/TooltipDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { tooltipConfig, type TooltipProduct } from "./tooltip.demo-data";
import "@simple-table/react/styles.css";

const TooltipDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable<TooltipProduct>
      columns={tooltipConfig.headers}
      rows={tooltipConfig.rows}
      height={height}
      theme={theme}
      columnResizing={tooltipConfig.tableProps.columnResizing}
      columnReordering={tooltipConfig.tableProps.columnReordering}
      selectableCells={tooltipConfig.tableProps.selectableCells}
      getRowId={({ row }) => row.id}
    />
  );
};

export default TooltipDemo;

// svelte/tooltip/src/demos/tooltip/TooltipDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { tooltipConfig } from "./tooltip.demo-data";
  import type { TooltipProduct } from "./tooltip.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const getRowId = ({ row }: GetRowIdParams<TooltipProduct>) => row.id;
</script>

<SimpleTable
  columns={tooltipConfig.headers}
  rows={tooltipConfig.rows}
  getRowId={getRowId}
  {height}
  {theme}
  columnResizing={true}
  columnReordering={true}
  selectableCells={true}
/>
