// svelte/crm/src/demos/crm/CrmSignalCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { CRMLead } from "./crm.demo-data";
  import { crmCellColors } from "./crm-demo-stores";

  let { row }: CellRendererProps<CRMLead> = $props();
  const colors = $derived($crmCellColors);
</script>

<div>
  <div style="color:{colors.textSecondary};margin-bottom:4px;font-size:0.875rem;">
    🧠 Just engaged with a
    <!-- svelte-ignore a11y_invalid_attribute -->
    <a href="#" style="color:#0077b5;text-decoration:underline;cursor:pointer;" onclick={(e) => e.preventDefault()}
      >post</a>
  </div>
  <div style="font-size:12px;color:{colors.textTertiary};">
    <span style="font-weight:600;">Keyword:</span>
    {` ${row.signal}`}
  </div>
</div>

// packages/examples/angular/src/demos/crm/crm-signal-cell.component.ts
import { Component, Input } from "@angular/core";
import type {  } from "@simple-table/angular";
import type { CRMLead } from "./crm.demo-data";
import { crmCellPalette } from "./crm-demo-context";

@Component({
  standalone: true,
  selector: "demo-crm-signal",
  template: `
    <div>
      <div style="margin-bottom:4px;font-size:0.875rem;" [style.color]="palette().textSecondary">
        🧠 Just engaged with a
        <a href="#" style="color:#0077b5;text-decoration:underline;cursor:pointer;" (click)="$event.preventDefault()">post</a>
      </div>
      <div style="font-size:12px;" [style.color]="palette().textTertiary">
        <span style="font-weight:600;">Keyword:</span>
        {{ " " + d.signal }}
      </div>
    </div>
  `,
})
export class CrmSignalCellComponent {
  @Input({ required: true }) row!: CRMLead;

  protected readonly palette = crmCellPalette;
}
