// svelte/column-alignment/src/demos/column-alignment/ColumnAlignmentDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnAlignmentConfig } from "./column-alignment.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={columnAlignmentConfig.headers}
  rows={columnAlignmentConfig.rows}
  {height}
  {theme}
/>

// vue/column-alignment/src/demos/column-alignment/ColumnAlignmentDemo.vue
<template>
  <SimpleTable
    :columns="columnAlignmentConfig.headers"
    :rows="columnAlignmentConfig.rows"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>
