// react/column-alignment/src/demos/column-alignment/ColumnAlignmentDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/react/styles.css";

const ColumnAlignmentDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      columns={columnAlignmentConfig.headers}
      rows={columnAlignmentConfig.rows}
      height={height}
      theme={theme}
    />
  );
};

export default ColumnAlignmentDemo;

// svelte/column-alignment/src/demos/column-alignment/ColumnAlignmentDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnAlignmentConfig } from "./column-alignment.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={columnAlignmentConfig.headers}
  rows={columnAlignmentConfig.rows}
  {height}
  {theme}
/>
