// packages/examples/react/src/demos/collapsible-columns/CollapsibleColumnsDemo.tsx
import { SimpleTable } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import {
  collapsibleColumnsConfig,
  type CollapsibleSalesRep,
} from "./collapsible-columns.demo-data";
import "@simple-table/react/styles.css";

const CollapsibleColumnsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable<CollapsibleSalesRep>
      columns={collapsibleColumnsConfig.headers}
      getRowId={({ row }) => row.id}
      rows={collapsibleColumnsConfig.rows}
      columnResizing
      enableColumnEditor
      selectableCells
      columnReordering
      height={height}
      theme={theme}
    />
  );
};

export default CollapsibleColumnsDemo;

// svelte/collapsible-columns/src/demos/collapsible-columns/CollapsibleColumnsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
  import type { CollapsibleSalesRep } from "./collapsible-columns.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const getRowId = ({ row }: GetRowIdParams<CollapsibleSalesRep>) => row.id;
</script>

<SimpleTable
  columns={collapsibleColumnsConfig.headers}
  rows={collapsibleColumnsConfig.rows}
  getRowId={getRowId}
  columnResizing={true}
  enableColumnEditor={true}
  selectableCells={true}
  columnReordering={true}
  {height}
  {theme}
/>
