// packages/examples/svelte/src/demos/csv-export/CsvExportDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteColumnDef } from "@simple-table/svelte";
  import { csvExportHeaders, csvExportData, csvExportConfig } from "./csv-export.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let tableRef: any;

  const headers: SvelteColumnDef[] = csvExportHeaders.map((h) => {
    if (h.accessor === "actions") {
      return {
        ...h,
        cellRenderer: () =>
          `<button style="background:#3b82f6;color:white;border:none;padding:4px 12px;border-radius:4px;cursor:pointer;font-size:12px;font-weight:bold">View</button>`,
      };
    }
    return { ...h };
  });

  function handleExport() {
    tableRef?.getAPI()?.exportToCSV();
  }

  function handleGetInfo() {
    const api = tableRef?.getAPI();
    if (!api) return;
    const rows = api.getAllRows();
    const hdrs = api.getHeaders();
    const totalRevenue = rows.reduce((sum: number, r: Record<string, unknown>) => sum + (Number(r.revenue) || 0), 0);
    alert(
      `Table Info:\n• ${rows.length} rows\n• ${hdrs.length} columns\n• Columns: ${hdrs.map((h: { label: string }) => h.label).join(", ")}\n• Total Revenue: $${totalRevenue.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    );
  }
</script>

<div>
  <div style="display: flex; gap: 8px; margin-bottom: 12px;">
    <button style="padding: 6px 16px" onclick={handleExport}>Export to CSV</button>
    <button style="padding: 6px 16px" onclick={handleGetInfo}>Get Table Info</button>
  </div>
  <SimpleTable
    bind:this={tableRef}
    columns={headers}
    rows={csvExportData}
    enableColumnEditor={csvExportConfig.tableProps.enableColumnEditor}
    selectableCells={csvExportConfig.tableProps.selectableCells}
    customTheme={csvExportConfig.tableProps.customTheme}
    {height}
    {theme}
  />
</div>

// packages/examples/solid/src/demos/csv-export/CsvExportDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme, TableAPI, SolidColumnDef } from "@simple-table/solid";
import { csvExportHeaders, csvExportData, csvExportConfig } from "./csv-export.demo-data";
import "@simple-table/solid/styles.css";

export default function CsvExportDemo(props: { height?: string | number; theme?: Theme }) {
  let tableRef: TableAPI | undefined;

  const headers: SolidColumnDef[] = csvExportHeaders.map((h) => {
    if (h.accessor === "actions") {
      return {
        ...h,
        cellRenderer: () => (
          <button
            type="button"
            style={{
              background: "#3b82f6",
              color: "white",
              border: "none",
              padding: "4px 12px",
              "border-radius": "4px",
              cursor: "pointer",
              "font-size": "12px",
              "font-weight": "bold",
            }}
          >
            View
          </button>
        ),
      };
    }
    return h;
  });

  const handleExport = () => {
    tableRef?.exportToCSV();
  };

  const handleGetInfo = () => {
    if (!tableRef) return;
    const rows = tableRef.getAllRows();
    const hdrs = tableRef.getHeaders();
    const totalRevenue = rows.reduce(
      (sum, r) => sum + (Number((r.row as { revenue?: unknown }).revenue) || 0),
      0,
    );
    alert(
      `Table Info:\n• ${rows.length} rows\n• ${hdrs.length} columns\n• Columns: ${hdrs.map((h) => h.label).join(", ")}\n• Total Revenue: $${totalRevenue.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
    );
  };

  return (
    <div>
      <div style={{ "margin-bottom": "12px", display: "flex", gap: "8px" }}>
        <button onClick={handleExport} style={{ padding: "6px 16px" }}>
          Export to CSV
        </button>
        <button onClick={handleGetInfo} style={{ padding: "6px 16px" }}>
          Get Table Info
        </button>
      </div>
      <SimpleTable
        ref={(api) => (tableRef = api)}
        columns={headers}
        rows={csvExportData}
        enableColumnEditor={csvExportConfig.tableProps.enableColumnEditor}
        selectableCells={csvExportConfig.tableProps.selectableCells}
        customTheme={csvExportConfig.tableProps.customTheme}
        height={props.height ?? "400px"}
        theme={props.theme}
      />
    </div>
  );
}
