// packages/examples/react/src/demos/cell-highlighting/CellHighlightingDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { cellHighlightingConfig } from "./cell-highlighting.demo-data";
import "@simple-table/react/styles.css";

const CellHighlightingDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      columns={cellHighlightingConfig.headers}
      rows={cellHighlightingConfig.rows}
      height={height}
      theme={theme}
      selectableCells={cellHighlightingConfig.tableProps.selectableCells}
      selectableColumns={cellHighlightingConfig.tableProps.selectableColumns}
    />
  );
};

export default CellHighlightingDemo;

// packages/examples/vue/src/demos/cell-highlighting/CellHighlightingDemo.vue
<template>
  <SimpleTable
    :columns="cellHighlightingConfig.headers"
    :rows="cellHighlightingConfig.rows"
    :height="height"
    :theme="theme"
    :selectable-cells="cellHighlightingConfig.tableProps.selectableCells"
    :selectable-columns="cellHighlightingConfig.tableProps.selectableColumns"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { cellHighlightingConfig } from "./cell-highlighting.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>
