// packages/examples/svelte/src/demos/value-formatter/ValueFormatterDemo.svelte
<script lang="ts">
  import { SimpleTable } from "simple-table-svelte";
  import type { Theme } from "simple-table-svelte";
  import { valueFormatterConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={valueFormatterConfig.headers}
  rows={valueFormatterConfig.rows}
  {height}
  {theme}
/>

// packages/examples/solid/src/demos/value-formatter/ValueFormatterDemo.tsx
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { valueFormatterConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

export default function ValueFormatterDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={valueFormatterConfig.headers}
      rows={valueFormatterConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
