// solid/analytics/src/demos/analytics/AnalyticsDemo.tsx
import { createEffect, createMemo, createSignal, For, onCleanup, Show } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { TableAPI, Theme } from "@simple-table/solid";
import { analyticsDemoConfig, analyticsPresets, type AnalyticsFactRow } from "./analytics.demo-data";
import "@simple-table/solid/styles.css";

function formatHeight(height?: string | number | null): string {
  if (height == null) return "100%";
  if (typeof height === "number") return `${height}px`;
  return height;
}

export default function AnalyticsDemo(props: {
  height?: string | number | null;
  theme?: Theme;
}) {
  const [activeId, setActiveId] = createSignal(analyticsPresets[0].id);
  const [tableHeightPx, setTableHeightPx] = createSignal<number | null>(null);
  let tableHost: HTMLDivElement | undefined;
  let tableApi: TableAPI<AnalyticsFactRow> | undefined;

  const active = createMemo(
    () => analyticsPresets.find((p) => p.id === activeId()) ?? analyticsPresets[0]
  );
  const isPivoted = createMemo(() => active().pivot != null);
  const nestedRows = createMemo(() => (active().pivot?.rows.length ?? 0) > 1);
  const isDark = () => props.theme === "dark" || props.theme === "modern-dark";
  const chromeBg = () => (isDark() ? "#0f172a" : "#f8fafc");
  const chromeBorder = () => (isDark() ? "#1e293b" : "#e2e8f0");
  const titleColor = () => (isDark() ? "#f1f5f9" : "#0f172a");
  const chipIdleBg = () => (isDark() ? "#1e293b" : "#e2e8f0");
  const chipIdleColor = () => (isDark() ? "#cbd5e1" : "#334155");
  const inputBorder = () => (isDark() ? "#334155" : "#cbd5e1");

  createEffect(() => {
    const el = tableHost;
    if (!el) return;
    const update = () => {
      setTableHeightPx(el.clientHeight);
      const mount = el.firstElementChild as HTMLElement | null;
      if (mount) {
        mount.style.height = "100%";
        mount.style.minHeight = "0";
      }
    };
    update();
    const ro = new ResizeObserver(update);
    ro.observe(el);
    onCleanup(() => ro.disconnect());
  });

  return (
    <div
      style={{
        display: "flex",
        "flex-direction": "column",
        width: "100%",
        height: formatHeight(props.height ?? "480px"),
        background: chromeBg(),
        border: `1px solid ${chromeBorder()}`,
        "border-radius": "8px",
        overflow: "hidden",
      }}
    >
      <div
        style={{
          padding: "16px 20px 12px",
          "border-bottom": `1px solid ${chromeBorder()}`,
          "flex-shrink": 0,
        }}
      >
        <div style={{ "margin-bottom": "10px" }}>
          <h2
            style={{
              margin: 0,
              "font-size": "18px",
              "font-weight": 650,
              color: titleColor(),
              "letter-spacing": "-0.02em",
            }}
          >
            Revenue Analytics
          </h2>
        </div>
        <div
          style={{
            display: "flex",
            "flex-wrap": "wrap",
            gap: "8px",
            "align-items": "center",
            "justify-content": "space-between",
            width: "100%",
          }}
        >
          <div style={{ display: "flex", "flex-wrap": "wrap", gap: "8px", "align-items": "center" }}>
            <For each={analyticsPresets}>
              {(preset) => {
                const selected = () => preset.id === activeId();
                return (
                  <button
                    type="button"
                    onClick={() => setActiveId(preset.id)}
                    style={{
                      padding: "7px 12px",
                      "border-radius": "6px",
                      border: "none",
                      cursor: "pointer",
                      "font-size": "13px",
                      "font-weight": 550,
                      background: selected() ? "#2563eb" : chipIdleBg(),
                      color: selected() ? "#fff" : chipIdleColor(),
                    }}
                  >
                    {preset.label}
                  </button>
                );
              }}
            </For>
          </div>
          <button
            type="button"
            onClick={() => tableApi?.exportToCSV()}
            style={{
              padding: "7px 12px",
              "border-radius": "6px",
              border: `1px solid ${inputBorder()}`,
              cursor: "pointer",
              "font-size": "13px",
              "font-weight": 550,
              background: chipIdleBg(),
              color: chipIdleColor(),
            }}
          >
            Export CSV
          </button>
        </div>
      </div>
      <div
        style={{
          flex: 1,
          "min-height": 0,
          padding: "12px 20px 20px",
          display: "flex",
          "flex-direction": "column",
        }}
      >
        <div ref={(el) => (tableHost = el)} style={{ flex: 1, "min-height": 0 }}>
          <Show when={tableHeightPx() != null ? `${activeId()}:${tableHeightPx()}` : null} keyed>
            <SimpleTable
              ref={(api) => {
                tableApi = api;
              }}
              autoExpandColumns
              columnBorders
              columnReordering
              columnResizing
              copyHeadersToClipboard
              columns={analyticsDemoConfig.headers}
              enableColumnEditor
              enableStickyParents={nestedRows()}
              expandAll={nestedRows()}
              getRowId={({ row }) => {
                const id = row.id;
                return id == null ? undefined : String(id);
              }}
              height={tableHeightPx()!}
              includeHeadersInCSVExport
              initialSortColumn={isPivoted() ? undefined : "sales"}
              initialSortDirection={isPivoted() ? undefined : "desc"}
              pivot={active().pivot}
              rows={analyticsDemoConfig.rows}
              selectableCells
              theme={props.theme}
              hoverRowBackground
              oddEvenRowBackground
            />
          </Show>
        </div>
      </div>
    </div>
  );
}

// packages/examples/svelte/src/demos/analytics/AnalyticsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { TableAPI, Theme } from "@simple-table/svelte";
  import { analyticsDemoConfig, analyticsPresets } from "./analytics.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "480px", theme }: { height?: string | number | null; theme?: Theme } = $props();

  let activeId = $state(analyticsPresets[0].id);
  let tableRef = $state<{ getAPI: () => TableAPI | null } | null>(null);
  const active = $derived(analyticsPresets.find((p) => p.id === activeId) ?? analyticsPresets[0]);
  const isPivoted = $derived(active.pivot != null);
  const nestedRows = $derived((active.pivot?.rows.length ?? 0) > 1);
  const isDark = $derived(theme === "dark" || theme === "modern-dark");
  const chromeBg = $derived(isDark ? "#0f172a" : "#f8fafc");
  const chromeBorder = $derived(isDark ? "#1e293b" : "#e2e8f0");
  const titleColor = $derived(isDark ? "#f1f5f9" : "#0f172a");
  const chipIdleBg = $derived(isDark ? "#1e293b" : "#e2e8f0");
  const chipIdleColor = $derived(isDark ? "#cbd5e1" : "#334155");
  const inputBorder = $derived(isDark ? "#334155" : "#cbd5e1");
  const formatHeight = $derived(
    height == null ? "100%" : typeof height === "number" ? `${height}px` : height
  );

  function getRowId({ row }: { row: { id?: unknown } }) {
    return row.id == null ? undefined : String(row.id);
  }
</script>

<div
  style="display: flex; flex-direction: column; width: 100%; height: {formatHeight}; background: {chromeBg}; border: 1px solid {chromeBorder}; border-radius: 8px; overflow: hidden"
>
  <div style="padding: 16px 20px 12px; border-bottom: 1px solid {chromeBorder}; flex-shrink: 0">
    <div style="margin-bottom: 10px">
      <h2
        style="margin: 0; font-size: 18px; font-weight: 650; color: {titleColor}; letter-spacing: -0.02em"
      >
        Revenue Analytics
      </h2>
    </div>
    <div
      style="display: flex; flex-wrap: wrap; gap: 8px; align-items: center; justify-content: space-between; width: 100%"
    >
      <div style="display: flex; flex-wrap: wrap; gap: 8px; align-items: center">
        {#each analyticsPresets as preset}
          <button
            type="button"
            onclick={() => (activeId = preset.id)}
            style="padding: 7px 12px; border-radius: 6px; border: none; cursor: pointer; font-size: 13px; font-weight: 550; background: {preset.id ===
            activeId
              ? '#2563eb'
              : chipIdleBg}; color: {preset.id === activeId ? '#fff' : chipIdleColor}"
          >
            {preset.label}
          </button>
        {/each}
      </div>
      <button
        type="button"
        onclick={() => tableRef?.getAPI()?.exportToCSV()}
        style="padding: 7px 12px; border-radius: 6px; border: 1px solid {inputBorder}; cursor: pointer; font-size: 13px; font-weight: 550; background: {chipIdleBg}; color: {chipIdleColor}"
      >
        Export CSV
      </button>
    </div>
  </div>
  <div
    style="flex: 1; min-height: 0; padding: 12px 20px 20px; display: flex; flex-direction: column"
  >
    <div style="flex: 1; min-height: 0; height: 100%">
      {#key activeId}
        <SimpleTable
          bind:this={tableRef}
          autoExpandColumns={true}
          columnBorders={true}
          columnReordering={true}
          columnResizing={true}
          copyHeadersToClipboard={true}
          columns={analyticsDemoConfig.headers}
          enableColumnEditor={true}
          enableStickyParents={nestedRows}
          expandAll={nestedRows}
          {getRowId}
          height="100%"
          includeHeadersInCSVExport={true}
          initialSortColumn={isPivoted ? undefined : "sales"}
          initialSortDirection={isPivoted ? undefined : "desc"}
          pivot={active.pivot}
          rows={analyticsDemoConfig.rows}
          selectableCells={true}
          {theme}
          hoverRowBackground={true}
          oddEvenRowBackground={true}
        />
      {/key}
    </div>
  </div>
</div>
