// solid/quick-filter/src/demos/quick-filter/QuickFilterDemo.tsx
import { createSignal } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, QuickFilterMode } from "@simple-table/solid";
import { quickFilterConfig } from "./quick-filter.demo-data";
import "@simple-table/solid/styles.css";

export default function QuickFilterDemo(props: { height?: string | number; theme?: Theme }) {
  const [searchText, setSearchText] = createSignal("");
  const [filterMode, setFilterMode] = createSignal<QuickFilterMode>("simple");
  const [caseSensitive, setCaseSensitive] = createSignal(false);

  const modeBtn = (mode: QuickFilterMode, label: string) => ({
    padding: "6px 14px",
    "border-radius": "6px",
    border: filterMode() === mode ? "2px solid #3b82f6" : "1px solid #d1d5db",
    background: filterMode() === mode ? "#eff6ff" : "#fff",
    color: filterMode() === mode ? "#1d4ed8" : "#374151",
    "font-weight": filterMode() === mode ? 600 : 400,
    cursor: "pointer",
    "font-size": "13px",
  });

  return (
    <div>
      <div style={{ display: "flex", "flex-wrap": "wrap", gap: "8px", "margin-bottom": "12px", "align-items": "center" }}>
        <input
          type="text"
          placeholder="Search..."
          value={searchText()}
          onInput={(e) => setSearchText(e.currentTarget.value)}
          style={{
            padding: "6px 12px",
            "border-radius": "6px",
            border: "1px solid #d1d5db",
            "font-size": "13px",
            "min-width": "200px",
          }}
        />
        <button onClick={() => setFilterMode("simple")} style={modeBtn("simple", "Simple")}>
          Simple
        </button>
        <button onClick={() => setFilterMode("smart")} style={modeBtn("smart", "Smart")}>
          Smart
        </button>
        <button
          onClick={() => setCaseSensitive((prev) => !prev)}
          style={{
            padding: "6px 14px",
            "border-radius": "6px",
            border: caseSensitive() ? "2px solid #3b82f6" : "1px solid #d1d5db",
            background: caseSensitive() ? "#eff6ff" : "#fff",
            color: caseSensitive() ? "#1d4ed8" : "#374151",
            "font-weight": caseSensitive() ? 600 : 400,
            cursor: "pointer",
            "font-size": "13px",
          }}
        >
          Case Sensitive
        </button>
      </div>
      <SimpleTable
        columns={quickFilterConfig.headers}
        getRowId={({ row }) => row.id}
        rows={quickFilterConfig.rows}
        height={props.height ?? "400px"}
        theme={props.theme}
        quickFilter={{ text: searchText(), mode: filterMode(), caseSensitive: caseSensitive() }}
      />
    </div>
  );
}

// svelte/quick-filter/src/demos/quick-filter/QuickFilterDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, QuickFilterMode, GetRowIdParams } from "@simple-table/svelte";
  import { quickFilterConfig } from "./quick-filter.demo-data";
  import type { QuickFilterEmployee } from "./quick-filter.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let searchText = $state("");
  let filterMode: QuickFilterMode = $state("simple");
  let caseSensitive = $state(false);

  const getRowId = ({ row }: GetRowIdParams<QuickFilterEmployee>) => row.id;
</script>

<div>
  <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px; align-items: center">
    <input
      type="text"
      placeholder="Search..."
      bind:value={searchText}
      style="padding: 6px 12px; border-radius: 6px; border: 1px solid #d1d5db; font-size: 13px; min-width: 200px"
    />
    <button
      onclick={() => (filterMode = "simple")}
      style="padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; border: {filterMode === 'simple' ? '2px solid #3b82f6' : '1px solid #d1d5db'}; background: {filterMode === 'simple' ? '#eff6ff' : '#fff'}; color: {filterMode === 'simple' ? '#1d4ed8' : '#374151'}; font-weight: {filterMode === 'simple' ? 600 : 400}"
    >
      Simple
    </button>
    <button
      onclick={() => (filterMode = "smart")}
      style="padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; border: {filterMode === 'smart' ? '2px solid #3b82f6' : '1px solid #d1d5db'}; background: {filterMode === 'smart' ? '#eff6ff' : '#fff'}; color: {filterMode === 'smart' ? '#1d4ed8' : '#374151'}; font-weight: {filterMode === 'smart' ? 600 : 400}"
    >
      Smart
    </button>
    <button
      onclick={() => (caseSensitive = !caseSensitive)}
      style="padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; border: {caseSensitive ? '2px solid #3b82f6' : '1px solid #d1d5db'}; background: {caseSensitive ? '#eff6ff' : '#fff'}; color: {caseSensitive ? '#1d4ed8' : '#374151'}; font-weight: {caseSensitive ? 600 : 400}"
    >
      Case Sensitive
    </button>
  </div>
  <SimpleTable
    columns={quickFilterConfig.headers}
    rows={quickFilterConfig.rows}
    getRowId={getRowId}
    {height}
    {theme}
    quickFilter={{ text: searchText, mode: filterMode, caseSensitive }}
  />
</div>
