// packages/angular/src/tdgp/useTdgpTable.ts
import { DestroyRef, computed, effect, inject, signal, untracked } from "@angular/core";
import {
  createTdgpTableSource,
  type TdgpTableSourceOptions,
} from "simple-table-core";
import type { AngularColumnDef, AngularDefaultRowData } from "../types";

export type UseTdgpTableOptions<TData extends AngularDefaultRowData = AngularDefaultRowData> = Omit<
  TdgpTableSourceOptions<TData>,
  "columns"
> & {
  columns: AngularColumnDef<TData>[];
};

function resolveOptions<TData extends AngularDefaultRowData>(
  options: UseTdgpTableOptions<TData> | (() => UseTdgpTableOptions<TData>),
): UseTdgpTableOptions<TData> {
  return typeof options === "function" ? options() : options;
}

function toSourceOptions<TData extends AngularDefaultRowData>(
  options: UseTdgpTableOptions<TData>,
): TdgpTableSourceOptions<TData> {
  return {
    ...options,
    columns: options.columns as TdgpTableSourceOptions<TData>["columns"],
  };
}

/**
 * Loads rows from a TDGP server and returns Simple Table props for
 * server-side paging, sorting, filtering, and optional grouping.
 *
 * Call from an injection context (component field or constructor). Pass a
 * getter if dataset, page size, or other query options should update. Bind
 * `[tableProps]` on `<simple-table>` for paging, sort, and filter.
 */
export function useTdgpTable<TData extends AngularDefaultRowData = AngularDefaultRowData>(
  options: UseTdgpTableOptions<TData> | (() => UseTdgpTableOptions<TData>),
) {
  const destroyRef = inject(DestroyRef);
  const source = createTdgpTableSource(toSourceOptions(resolveOptions(options)));
  const snapshot = signal(source.getSnapshot());

  const unsubscribe = source.subscribe(() => {
    snapshot.set(source.getSnapshot());
  });

  effect(() => {
    const next = resolveOptions(options);
    untracked(() => {
      source.applyOptions(toSourceOptions(next));
    });
  });

  source.start();

  destroyRef.onDestroy(() => {
    source.stop();
    unsubscribe();
  });

  return {
    rows: computed(() => snapshot().rows),
    columns: computed(() => snapshot().columns as AngularColumnDef<TData>[]),
    tableProps: computed(() => snapshot().tableProps),
    error: computed(() => snapshot().error),
    isLoading: computed(() => snapshot().isLoading),
    totalRowCount: computed(() => snapshot().totalRowCount),
  };
}

// packages/solid/src/tdgp/useTdgpTable.ts
import { createEffect, createSignal, onCleanup, onMount, type Accessor } from "solid-js";
import {
  createTdgpTableSource,
  type TdgpTableSourceOptions,
} from "simple-table-core";
import type { SolidColumnDef, SolidDefaultRowData } from "../types";

export type UseTdgpTableOptions<TData extends SolidDefaultRowData = SolidDefaultRowData> = Omit<
  TdgpTableSourceOptions<TData>,
  "columns"
> & {
  columns: SolidColumnDef<TData>[];
};

function resolveOptions<TData extends SolidDefaultRowData>(
  options: UseTdgpTableOptions<TData> | Accessor<UseTdgpTableOptions<TData>>,
): UseTdgpTableOptions<TData> {
  return typeof options === "function"
    ? (options as Accessor<UseTdgpTableOptions<TData>>)()
    : options;
}

function toSourceOptions<TData extends SolidDefaultRowData>(
  options: UseTdgpTableOptions<TData>,
): TdgpTableSourceOptions<TData> {
  return {
    ...options,
    columns: options.columns as TdgpTableSourceOptions<TData>["columns"],
  };
}

/**
 * Loads rows from a TDGP server and returns Simple Table props for
 * server-side paging, sorting, filtering, and optional grouping.
 *
 * Pass a getter if dataset, page size, or other query options should update.
 * A new client or columns object does not reload. A change to dataset, page
 * size, primary key, group fields, or aggregations does.
 */
export function useTdgpTable<TData extends SolidDefaultRowData = SolidDefaultRowData>(
  options: UseTdgpTableOptions<TData> | Accessor<UseTdgpTableOptions<TData>>,
) {
  const source = createTdgpTableSource(toSourceOptions(resolveOptions(options)));
  const [snapshot, setSnapshot] = createSignal(source.getSnapshot(), { equals: false });

  const unsubscribe = source.subscribe(() => {
    setSnapshot(source.getSnapshot());
  });

  createEffect(() => {
    source.applyOptions(toSourceOptions(resolveOptions(options)));
  });

  onMount(() => {
    source.start();
  });

  onCleanup(() => {
    source.stop();
    unsubscribe();
  });

  return {
    rows: () => snapshot().rows,
    columns: () => snapshot().columns as SolidColumnDef<TData>[],
    tableProps: () => snapshot().tableProps,
    error: () => snapshot().error,
    isLoading: () => snapshot().isLoading,
    totalRowCount: () => snapshot().totalRowCount,
  };
}
