// svelte/loading-state/src/demos/loading-state/LoadingStateDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { onMount } from "svelte";
  import { loadingStateConfig } from "./loading-state.demo-data";
  import type { LoadingStateEmployee } from "./loading-state.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let isLoading = $state(true);
  let data = $state<LoadingStateEmployee[]>([]);

  const getRowId = ({ row }: GetRowIdParams<LoadingStateEmployee>) => row.id;

  function loadData() {
    isLoading = true;
    data = [];
    setTimeout(() => {
      data = [...loadingStateConfig.rows];
      isLoading = false;
    }, 2000);
  }

  onMount(() => {
    loadData();
  });
</script>

<div>
  <div style="margin-bottom: 12px">
    <button
      onclick={loadData}
      disabled={isLoading}
      style="padding: 6px 16px; cursor: {isLoading ? 'not-allowed' : 'pointer'}"
    >
      {isLoading ? "Loading\u2026" : "Reload Data"}
    </button>
  </div>
  <SimpleTable
    columns={loadingStateConfig.headers}
    rows={data}
    getRowId={getRowId}
    {isLoading}
    {height}
    {theme}
  />
</div>

// packages/examples/vue/src/demos/loading-state/LoadingStateDemo.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { SimpleTable } from "@simple-table/vue";
import type { Theme, GetRowIdParams } from "@simple-table/vue";
import { loadingStateConfig } from "./loading-state.demo-data";
import type { LoadingStateEmployee } from "./loading-state.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const isLoading = ref(true);
const data = ref<LoadingStateEmployee[]>([]);

const getRowId = ({ row }: GetRowIdParams<LoadingStateEmployee>) => row.id;

function loadData() {
  isLoading.value = true;
  data.value = [];
  setTimeout(() => {
    data.value = [...loadingStateConfig.rows];
    isLoading.value = false;
  }, 2000);
}

onMounted(() => {
  loadData();
});
</script>

<template>
  <div>
    <div style="margin-bottom: 12px">
      <button
        @click="loadData"
        :disabled="isLoading"
        :style="{ padding: '6px 16px', cursor: isLoading ? 'not-allowed' : 'pointer' }"
      >
        {{ isLoading ? 'Loading\u2026' : 'Reload Data' }}
      </button>
    </div>
    <SimpleTable
      :columns="loadingStateConfig.headers"
      :get-row-id="getRowId"
      :rows="data"
      :is-loading="isLoading"
      :height="props.height"
      :theme="props.theme"
    />
  </div>
</template>
