// packages/examples/solid/src/demos/row-height/RowHeightDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { rowHeightConfig } from "./row-height.demo-data";
import "@simple-table/solid/styles.css";

export default function RowHeightDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      columns={rowHeightConfig.headers}
      rows={rowHeightConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      customTheme={rowHeightConfig.tableProps.customTheme}
    />
  );
}

// svelte/row-height/src/demos/row-height/RowHeightDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { rowHeightConfig } from "./row-height.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={rowHeightConfig.headers}
  rows={rowHeightConfig.rows}
  {height}
  {theme}
  customTheme={rowHeightConfig.tableProps.customTheme}
/>
