// packages/examples/react/src/demos/column-sorting/ColumnSortingDemo.tsx
import { SimpleTable } from "simple-table-react";
import type { Theme } from "simple-table-react";
import { columnSortingConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

const ColumnSortingDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={columnSortingConfig.headers}
      rows={columnSortingConfig.rows}
      height={height}
      theme={theme}
      initialSortColumn={columnSortingConfig.tableProps.initialSortColumn}
      initialSortDirection={columnSortingConfig.tableProps.initialSortDirection}
    />
  );
};

export default ColumnSortingDemo;

// packages/examples/svelte/src/demos/column-sorting/ColumnSortingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "simple-table-svelte";
  import type { Theme } from "simple-table-svelte";
  import { columnSortingConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={columnSortingConfig.headers}
  rows={columnSortingConfig.rows}
  {height}
  {theme}
  initialSortColumn={columnSortingConfig.tableProps.initialSortColumn}
  initialSortDirection={columnSortingConfig.tableProps.initialSortDirection}
/>
