// packages/examples/solid/src/demos/column-sorting/ColumnSortingDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnSortingConfig } from "./column-sorting.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnSortingDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      columns={columnSortingConfig.headers}
      rows={columnSortingConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      initialSortColumn="age"
      initialSortDirection="desc"
    />
  );
}

// packages/examples/svelte/src/demos/column-sorting/ColumnSortingDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnSortingConfig } from "./column-sorting.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={columnSortingConfig.headers}
  rows={columnSortingConfig.rows}
  {height}
  {theme}
  initialSortColumn="age"
  initialSortDirection="desc"
/>
