// packages/examples/react/src/demos/collapsible-columns/CollapsibleColumnsDemo.tsx
import { SimpleTable } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { collapsibleColumnsConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

const CollapsibleColumnsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={collapsibleColumnsConfig.headers}
      rows={collapsibleColumnsConfig.rows}
      columnResizing
      height={height}
      theme={theme}
    />
  );
};

export default CollapsibleColumnsDemo;

// packages/examples/svelte/src/demos/collapsible-columns/CollapsibleColumnsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { collapsibleColumnsConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={collapsibleColumnsConfig.headers}
  rows={collapsibleColumnsConfig.rows}
  columnResizing={collapsibleColumnsConfig.tableProps.columnResizing}
  {height}
  {theme}
/>
