// packages/examples/svelte/src/demos/external-sort/ExternalSortDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme, SortColumn } from "@simple-table/svelte";
  import { externalSortConfig } from "./external-sort.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let sortConfig = $state<SortColumn | null>(null);

  let sortedRows = $derived.by(() => {
    const data = [...externalSortConfig.rows];
    if (!sortConfig) return data;

    const accessor = sortConfig.key.accessor as string;
    const dir = sortConfig.direction === "asc" ? 1 : -1;

    return data.sort((a, b) => {
      const aVal = a[accessor];
      const bVal = b[accessor];
      if (aVal == null && bVal == null) return 0;
      if (aVal == null) return dir;
      if (bVal == null) return -dir;
      if (typeof aVal === "string" && typeof bVal === "string") return dir * aVal.localeCompare(bVal);
      return dir * (Number(aVal) - Number(bVal));
    });
  });

  function handleSortChange(sort: SortColumn | null) {
    sortConfig = sort;
  }
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(externalSortConfig.headers)}
  rows={sortedRows}
  externalSortHandling={true}
  columnResizing={externalSortConfig.tableProps.columnResizing}
  onSortChange={handleSortChange}
  {height}
  {theme}
/>

// packages/examples/vue/src/demos/external-sort/ExternalSortDemo.vue
<template>
  <SimpleTable
    :default-headers="defaultHeadersFromCore(externalSortConfig.headers)"
    :rows="sortedRows"
    :external-sort-handling="true"
    :column-resizing="externalSortConfig.tableProps.columnResizing"
    :height="height"
    :theme="theme"
    @sort-change="handleSortChange"
  />
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/vue";
import type { Theme, SortColumn } from "@simple-table/vue";
import { externalSortConfig } from "./external-sort.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const sortConfig = ref<SortColumn | null>(null);

const sortedRows = computed(() => {
  const data = [...externalSortConfig.rows];
  const sort = sortConfig.value;
  if (!sort) return data;

  const accessor = sort.key.accessor as string;
  const dir = sort.direction === "asc" ? 1 : -1;

  return data.sort((a, b) => {
    const aVal = a[accessor];
    const bVal = b[accessor];
    if (aVal == null && bVal == null) return 0;
    if (aVal == null) return dir;
    if (bVal == null) return -dir;
    if (typeof aVal === "string" && typeof bVal === "string") return dir * aVal.localeCompare(bVal);
    return dir * (Number(aVal) - Number(bVal));
  });
});

function handleSortChange(sort: SortColumn | null) {
  sortConfig.value = sort;
}
</script>
