// svelte/dynamic-row-loading/src/demos/dynamic-row-loading/DynamicRowLoadingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, OnRowGroupExpandProps, GetRowIdParams } from "@simple-table/svelte";
  import {
    dynamicRowLoadingConfig,
    generateInitialRegions,
    fetchStoresForRegion,
    fetchProductsForStore,
  } from "./dynamic-row-loading.demo-data";
  import type { DynamicRegion, DynamicTreeRow } from "./dynamic-row-loading.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let rows = $state<DynamicRegion[]>(generateInitialRegions());
  const getRowId = ({ row }: GetRowIdParams<DynamicTreeRow>) => row.id;

  async function handleRowExpand({
    row,
    depth,
    groupingKey,
    isExpanded,
    setLoading,
    setError,
    setEmpty,
    rowIndexPath,
  }: OnRowGroupExpandProps<DynamicTreeRow>) {
    if (!isExpanded) return;
    if (groupingKey === "stores" && row.type === "region" && row.stores && row.stores.length > 0) {
      return;
    }
    if (groupingKey === "products" && row.type === "store" && row.products && row.products.length > 0) {
      return;
    }

    try {
      if (depth === 0 && groupingKey === "stores" && row.type === "region") {
        setLoading(true);
        const stores = await fetchStoresForRegion(row.id);
        setLoading(false);
        if (stores.length === 0) {
          setEmpty(true, "No stores found");
          return;
        }
        const newRows = [...rows];
        newRows[rowIndexPath[0]] = { ...newRows[rowIndexPath[0]], stores };
        rows = newRows;
      } else if (depth === 1 && groupingKey === "products" && row.type === "store") {
        setLoading(true);
        const products = await fetchProductsForStore(row.id);
        setLoading(false);
        if (products.length === 0) {
          setEmpty(true, "No products found");
          return;
        }
        const newRows = [...rows];
        const region = newRows[rowIndexPath[0]];
        if (region.stores && region.stores[rowIndexPath[1]]) {
          region.stores[rowIndexPath[1]] = { ...region.stores[rowIndexPath[1]], products };
        }
        rows = newRows;
      }
    } catch (error) {
      setLoading(false);
      setError(error instanceof Error ? error.message : "Failed to load data");
    }
  }
</script>

<SimpleTable
  columnResizing={dynamicRowLoadingConfig.tableProps.columnResizing}
  columns={dynamicRowLoadingConfig.headers}
  enableColumnEditor={dynamicRowLoadingConfig.tableProps.enableColumnEditor}
  expandAll={dynamicRowLoadingConfig.tableProps.expandAll}
  {getRowId}
  {height}
  onRowGroupExpand={handleRowExpand}
  rowGrouping={dynamicRowLoadingConfig.tableProps.rowGrouping}
  rows={rows}
  selectableCells={dynamicRowLoadingConfig.tableProps.selectableCells}
  {theme}
  oddEvenRowBackground={dynamicRowLoadingConfig.tableProps.oddEvenRowBackground}
/>

// react/dynamic-row-loading/src/demos/dynamic-row-loading/DynamicRowLoadingDemo.tsx
import { useState, useCallback } from "react";
import {SimpleTable} from "@simple-table/react";import type { Theme, OnRowGroupExpandProps } from "@simple-table/react";
import {
  dynamicRowLoadingConfig,
  generateInitialRegions,
  fetchStoresForRegion,
  fetchProductsForStore,
} from "./dynamic-row-loading.demo-data";
import type { DynamicRegion, DynamicStore } from "./dynamic-row-loading.demo-data";
import "@simple-table/react/styles.css";

const DynamicRowLoadingDemo = ({ height = "400px", theme }: { height?: string | number; theme?: Theme }) => {
  const [rows, setRows] = useState<DynamicRegion[]>(() => generateInitialRegions());

  const handleRowExpand = useCallback(
    async ({ row, depth, groupingKey, isExpanded, setLoading, setError, setEmpty, rowIndexPath }: OnRowGroupExpandProps) => {
      if (!isExpanded) return;
      if (groupingKey && row[groupingKey] && (row[groupingKey] as unknown[]).length > 0) return;

      try {
        if (depth === 0 && groupingKey === "stores") {
          setLoading(true);
          const region = row as DynamicRegion;
          const stores = await fetchStoresForRegion(region.id);
          setLoading(false);
          if (stores.length === 0) { setEmpty(true, "No stores found for this region"); return; }
          setRows((prevRows) => {
            const newRows = [...prevRows];
            newRows[rowIndexPath[0]].stores = stores;
            return newRows;
          });
        } else if (depth === 1 && groupingKey === "products") {
          setLoading(true);
          const store = row as DynamicStore;
          const products = await fetchProductsForStore(store.id);
          setLoading(false);
          if (products.length === 0) { setEmpty(true, "No products found for this store"); return; }
          setRows((prevRows) => {
            const newRows = [...prevRows];
            const region = newRows[rowIndexPath[0]];
            if (region.stores && region.stores[rowIndexPath[1]]) {
              region.stores[rowIndexPath[1]].products = products;
            }
            return newRows;
          });
        }
      } catch (error) {
        setLoading(false);
        setError(error instanceof Error ? error.message : "Failed to load data");
      }
    },
    [],
  );

  return (
    <SimpleTable
      columnResizing={dynamicRowLoadingConfig.tableProps.columnResizing}
      columns={dynamicRowLoadingConfig.headers}
      enableColumnEditor={dynamicRowLoadingConfig.tableProps.enableColumnEditor}
      expandAll={dynamicRowLoadingConfig.tableProps.expandAll}
      height={height}
      onRowGroupExpand={handleRowExpand}
      rowGrouping={dynamicRowLoadingConfig.tableProps.rowGrouping}
      getRowId={dynamicRowLoadingConfig.tableProps.getRowId}
      rows={rows}
      selectableCells={dynamicRowLoadingConfig.tableProps.selectableCells}
      theme={theme}
      oddEvenRowBackground={dynamicRowLoadingConfig.tableProps.oddEvenRowBackground}
    />
  );
};

export default DynamicRowLoadingDemo;
