// solid/column-alignment/src/demos/column-alignment/ColumnAlignmentDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { columnAlignmentConfig } from "./column-alignment.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnAlignmentDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(columnAlignmentConfig.headers)}
      rows={columnAlignmentConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}

// packages/examples/svelte/src/demos/column-alignment/ColumnAlignmentDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { columnAlignmentConfig } from "./column-alignment.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(columnAlignmentConfig.headers)}
  rows={columnAlignmentConfig.rows}
  {height}
  {theme}
/>
