// packages/examples/solid/src/demos/cell-highlighting/CellHighlightingDemo.tsx
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { cellHighlightingConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

export default function CellHighlightingDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={cellHighlightingConfig.headers}
      rows={cellHighlightingConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      selectableCells
      selectableColumns
    />
  );
}

// packages/examples/svelte/src/demos/cell-highlighting/CellHighlightingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { cellHighlightingConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={cellHighlightingConfig.headers}
  rows={cellHighlightingConfig.rows}
  {height}
  {theme}
  selectableCells={true}
  selectableColumns={true}
/>
