// packages/examples/svelte/src/demos/column-filtering/ColumnFilteringDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnFilteringConfig } from "./column-filtering.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={columnFilteringConfig.headers}
  rows={columnFilteringConfig.rows}
  {height}
  {theme}
/>

// packages/examples/react/src/demos/column-filtering/ColumnFilteringDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { columnFilteringConfig } from "./column-filtering.demo-data";
import "@simple-table/react/styles.css";

const ColumnFilteringDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      columns={columnFilteringConfig.headers}
      rows={columnFilteringConfig.rows}
      height={height}
      theme={theme}
    />
  );
};

export default ColumnFilteringDemo;
