// packages/examples/solid/src/demos/column-pinning/ColumnPinningDemo.tsx
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { columnPinningConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

export default function ColumnPinningDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={columnPinningConfig.headers}
      rows={columnPinningConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      columnResizing
    />
  );
}

// packages/examples/svelte/src/demos/column-pinning/ColumnPinningDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { columnPinningConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={columnPinningConfig.headers}
  rows={columnPinningConfig.rows}
  {height}
  {theme}
  columnResizing={true}
/>
