// solid/nested-tables/src/demos/nested-tables/NestedTablesDemo.tsx
import { createMemo } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { nestedTablesConfig, generateNestedTablesData } from "./nested-tables.demo-data";
import "@simple-table/solid/styles.css";

export default function NestedTablesDemo(props: { height?: string | number; theme?: Theme }) {
  const sampleData = createMemo(() => generateNestedTablesData(25));

  return (
    <SimpleTable
      autoExpandColumns={nestedTablesConfig.tableProps.autoExpandColumns}
      columns={nestedTablesConfig.headers}
      rows={sampleData()}
      rowGrouping={nestedTablesConfig.tableProps.rowGrouping}
      getRowId={({ row }) => row.id}
      expandAll={nestedTablesConfig.tableProps.expandAll}
      columnResizing={nestedTablesConfig.tableProps.columnResizing}
      height={props.height ?? "500px"}
      theme={props.theme}
    />
  );
}

// react/nested-tables/src/demos/nested-tables/NestedTablesDemo.tsx
import { useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import {
  nestedTablesConfig,
  generateNestedTablesData,
} from "./nested-tables.demo-data";
import "@simple-table/react/styles.css";

const NestedTablesDemo = ({ height = "500px", theme }: { height?: string | number; theme?: Theme }) => {
  const sampleData = useMemo(() => generateNestedTablesData(25), []);

  return (
    <SimpleTable
      autoExpandColumns={nestedTablesConfig.tableProps.autoExpandColumns}
      columns={nestedTablesConfig.headers}
      rows={sampleData}
      rowGrouping={nestedTablesConfig.tableProps.rowGrouping}
      getRowId={({ row }) => row.id}
      expandAll={nestedTablesConfig.tableProps.expandAll}
      columnResizing={nestedTablesConfig.tableProps.columnResizing}
      height={height}
      theme={theme}
    />
  );
};

export default NestedTablesDemo;
