// packages/examples/angular/src/demos/crypto/crypto-demo.component.ts
import { Component, Input, ViewChild, AfterViewInit, OnDestroy } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularColumnDef, Row, Theme, TableAPI, CellValue } from "@simple-table/angular";
import { cryptoConfig, cryptoData } from "./crypto.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "crypto-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      #simpleTable
      [columns]="headers"
      [rows]="rows"
      [height]="height"
      [theme]="theme"
      [columnReordering]="true"
      [columnResizing]="true"
      [enableColumnEditor]="true"
      [selectableCells]="true"
      [cellUpdateFlash]="true"
      [customTheme]="customTheme"
    ></simple-table>
  `,
})
export class CryptoDemoComponent implements AfterViewInit, OnDestroy {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number = "70dvh";
  @Input() theme?: Theme;

  readonly headers: AngularColumnDef[] = cryptoConfig.headers;
  readonly rows: Row[] = cryptoConfig.rows;
  readonly customTheme = { headerHeight: 40, rowHeight: 48 };

  private cleanupFn?: () => void;

  ngAfterViewInit(): void {
    const TICK_MS = 90;
    const ROWS_PER_TICK = 6;
    
    function pickRandomSubset<T>(arr: T[], n: number): T[] {
      const copy = [...arr];
      for (let i = copy.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        const t = copy[i]!;
        copy[i] = copy[j]!;
        copy[j] = t;
      }
      return copy.slice(0, Math.min(n, copy.length));
    }
    
    function applyRowPatch(api: TableAPI, rowIndex: number, patch: Partial<Row>) {
      for (const accessor of Object.keys(patch)) {
        const newValue = patch[accessor];
        if (newValue === undefined) continue;
        api.updateData({ accessor, rowIndex, newValue: newValue as CellValue });
      }
    }
    
    function runTick(getApi: () => TableAPI | null | undefined, idToIndex: Map<string, number>) {
      const api = getApi();
      if (!api) return;
      const visible = api.getVisibleRows();
      if (!visible.length) return;
      for (const vr of pickRandomSubset(visible, ROWS_PER_TICK)) {
        const idx = idToIndex.get(String(vr.row.id));
        if (idx === undefined) continue;
        const currentPrice = vr.row.price as number;
        if (typeof currentPrice !== "number") continue;
        const drift = (Math.random() - 0.5) * 0.012;
        const newPrice = Math.max(currentPrice * (1 + drift), currentPrice * 0.0001);
        const round = newPrice >= 1 ? 1e2 : 1e6;
        const newPriceRounded = Math.round(newPrice * round) / round;
        const currentChange = (vr.row.change24h as number) ?? 0;
        const newChange = Math.round((currentChange + drift * 100) * 100) / 100;
        const history = vr.row.priceHistory as number[];
        const patch: Partial<Row> = { price: newPriceRounded, change24h: newChange };
        if (Array.isArray(history) && history.length > 0) {
          patch.priceHistory = [...history.slice(1), newPriceRounded];
        }
        applyRowPatch(api, idx, patch);
      }
    }
    
    const idToIndex = new Map<string, number>();
    for (let i = 0; i < cryptoData.length; i++) idToIndex.set(String(cryptoData[i]!.id), i);
    const intervalId = setInterval(() => runTick(() => this.tableRef?.getAPI() ?? null, idToIndex), TICK_MS);
    this.cleanupFn = () => clearInterval(intervalId);
  }

  ngOnDestroy(): void {
    this.cleanupFn?.();
  }
}

// packages/examples/svelte/src/demos/crypto/CryptoDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, TableAPI, Row, CellValue } from "@simple-table/svelte";
  import { cryptoConfig, cryptoData } from "./crypto.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "70dvh", theme }: { height?: string | number; theme?: Theme } = $props();
  let tableRef: any;

  const TICK_MS = 90;
  const ROWS_PER_TICK = 6;
  
  function pickRandomSubset<T>(arr: T[], n: number): T[] {
    const copy = [...arr];
    for (let i = copy.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const t = copy[i]!;
      copy[i] = copy[j]!;
      copy[j] = t;
    }
    return copy.slice(0, Math.min(n, copy.length));
  }
  
  function applyRowPatch(api: TableAPI, rowIndex: number, patch: Partial<Row>) {
    for (const accessor of Object.keys(patch)) {
      const newValue = patch[accessor];
      if (newValue === undefined) continue;
      api.updateData({ accessor, rowIndex, newValue: newValue as CellValue });
    }
  }
  
  function runTick(getApi: () => TableAPI | null | undefined, idToIndex: Map<string, number>) {
    const api = getApi();
    if (!api) return;
    const visible = api.getVisibleRows();
    if (!visible.length) return;
    for (const vr of pickRandomSubset(visible, ROWS_PER_TICK)) {
      const idx = idToIndex.get(String(vr.row.id));
      if (idx === undefined) continue;
      const currentPrice = vr.row.price as number;
      if (typeof currentPrice !== "number") continue;
      const drift = (Math.random() - 0.5) * 0.012;
      const newPrice = Math.max(currentPrice * (1 + drift), currentPrice * 0.0001);
      const round = newPrice >= 1 ? 1e2 : 1e6;
      const newPriceRounded = Math.round(newPrice * round) / round;
      const currentChange = (vr.row.change24h as number) ?? 0;
      const newChange = Math.round((currentChange + drift * 100) * 100) / 100;
      const history = vr.row.priceHistory as number[];
      const patch: Partial<Row> = { price: newPriceRounded, change24h: newChange };
      if (Array.isArray(history) && history.length > 0) {
        patch.priceHistory = [...history.slice(1), newPriceRounded];
      }
      applyRowPatch(api, idx, patch);
    }
  }
  

  $effect(() => {
    if (!tableRef) return;
    const idToIndex = new Map<string, number>();
    for (let i = 0; i < cryptoData.length; i++) idToIndex.set(String(cryptoData[i]!.id), i);
    const intervalId = setInterval(() => runTick(() => tableRef?.getAPI?.() ?? null, idToIndex), TICK_MS);
    return () => clearInterval(intervalId);
  });
</script>

<SimpleTable
  bind:this={tableRef}
  columns={cryptoConfig.headers}
  rows={cryptoConfig.rows}
  {height}
  {theme}
  columnReordering
  columnResizing
  enableColumnEditor
  selectableCells
  cellUpdateFlash
  customTheme={{ headerHeight: 40, rowHeight: 48 }}
/>
