// packages/examples/solid/src/demos/column-editor-custom-renderer/ColumnEditorCustomRendererDemo.tsx
import {
  SimpleTable,
  type ColumnEditorRowRendererProps,
  type SolidColumnEditorConfig,
  type Theme,
} from "@simple-table/solid";
import { createEffect, type JSX } from "solid-js";
import {
  columnEditorCustomRendererConfig,
  COLUMN_EDITOR_TEXT,
  COLUMN_EDITOR_SEARCH_PLACEHOLDER,
} from "./column-editor-custom-renderer.demo-data";
import "@simple-table/solid/styles.css";

function attach(slot: unknown, host: HTMLElement | undefined): void {
  if (!host) return;
  host.replaceChildren();
  if (slot == null) return;
  if (typeof slot === "string") {
    host.textContent = slot;
  } else if (slot instanceof Node) {
    host.appendChild(slot);
  }
}

function SlotHost(props: { slot: () => unknown; style?: JSX.CSSProperties | string }) {
  let host: HTMLSpanElement | undefined;
  createEffect(() => {
    attach(props.slot(), host);
  });
  return (
    <span
      ref={(el) => {
        host = el;
        attach(props.slot(), el);
      }}
      style={props.style}
    />
  );
}

const CustomRowRenderer = (p: ColumnEditorRowRendererProps) => (
  <div
    style={{
      display: "flex",
      "align-items": "center",
      gap: "8px",
      padding: "6px 8px",
      "border-radius": "6px",
      background: "#f8fafc",
      "margin-bottom": "4px",
    }}
  >
    {p.components.checkbox && <SlotHost slot={() => p.components.checkbox} />}
    <span style={{ flex: "1", "font-size": "13px", "font-weight": "500" }}>{p.header.label}</span>
    {p.components.dragIcon && (
      <SlotHost slot={() => p.components.dragIcon} style={{ cursor: "grab", opacity: "0.5" }} />
    )}
  </div>
);

const columnEditorConfig: SolidColumnEditorConfig = {
  text: COLUMN_EDITOR_TEXT,
  searchEnabled: true,
  searchPlaceholder: COLUMN_EDITOR_SEARCH_PLACEHOLDER,
  rowRenderer: CustomRowRenderer,
};

export default function ColumnEditorCustomRendererDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      columns={columnEditorCustomRendererConfig.headers}
      getRowId={({ row }) => row.id}
      rows={columnEditorCustomRendererConfig.rows}
      enableColumnEditor
      columnEditorConfig={columnEditorConfig}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}

// packages/examples/react/src/demos/column-editor-custom-renderer/ColumnEditorCustomRendererDemo.tsx
import { SimpleTable } from "@simple-table/react";
import type {
  Theme,
  ReactColumnEditorConfig,
  ColumnEditorRowRendererProps,
} from "@simple-table/react";
import {
  columnEditorCustomRendererConfig,
  type ColumnEditorCustomRendererEmployee,
} from "./column-editor-custom-renderer.demo-data";
import "@simple-table/react/styles.css";

const CustomRowRenderer = ({ header, components }: ColumnEditorRowRendererProps) => (
  <div
    style={{
      display: "flex",
      alignItems: "center",
      gap: 8,
      padding: "6px 8px",
      borderRadius: 6,
      background: "#f8fafc",
      marginBottom: 4,
    }}
  >
    {components.checkbox != null && <span>{components.checkbox}</span>}
    <span style={{ flex: 1, fontSize: 13, fontWeight: 500 }}>{header.label}</span>
    {components.dragIcon != null && (
      <span style={{ cursor: "grab", opacity: 0.5 }}>{components.dragIcon}</span>
    )}
  </div>
);

const columnEditorConfig: ReactColumnEditorConfig = {
  text: "Manage Columns",
  searchEnabled: true,
  searchPlaceholder: "Search columns…",
  rowRenderer: CustomRowRenderer,
};

const ColumnEditorCustomRendererDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable<ColumnEditorCustomRendererEmployee>
      columns={columnEditorCustomRendererConfig.headers}
      getRowId={({ row }) => row.id}
      rows={columnEditorCustomRendererConfig.rows}
      enableColumnEditor
      columnEditorConfig={columnEditorConfig}
      height={height}
      theme={theme}
    />
  );
};

export default ColumnEditorCustomRendererDemo;
