// react/column-reordering/src/demos/column-reordering/ColumnReorderingDemo.tsx
import { useState } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactColumnDef } from "@simple-table/react";
import { columnReorderingConfig, type CrewMember } from "./column-reordering.demo-data";
import "@simple-table/react/styles.css";

const ColumnReorderingDemo = ({
  height = "400px",
  theme
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [headers, setHeaders] = useState(() => [...columnReorderingConfig.headers]);

  const handleColumnOrderChange = (newHeaders: ReactColumnDef<CrewMember>[]) => {
    setHeaders(newHeaders);
  };

  return (
    <SimpleTable
      columnReordering={columnReorderingConfig.tableProps.columnReordering}
      columns={headers}
      rows={columnReorderingConfig.rows}
      height={height}
      theme={theme}
      getRowId={({ row }) => row.id}
      onColumnOrderChange={handleColumnOrderChange}
    />
  );
};

export default ColumnReorderingDemo;

// packages/examples/solid/src/demos/column-reordering/ColumnReorderingDemo.tsx
import { createSignal } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, SolidColumnDef } from "@simple-table/solid";
import { columnReorderingConfig, type CrewMember } from "./column-reordering.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnReorderingDemo(props: { height?: string | number; theme?: Theme }) {
  const [headers, setHeaders] = createSignal([...columnReorderingConfig.headers]);

  const handleColumnOrderChange = (newHeaders: SolidColumnDef<CrewMember>[]) => {
    setHeaders(newHeaders);
  };

  return (
    <SimpleTable
      columnReordering={columnReorderingConfig.tableProps.columnReordering}
      columns={headers()}
      getRowId={({ row }) => row.id}
      rows={columnReorderingConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      onColumnOrderChange={handleColumnOrderChange}
    />
  );
}
