// react/cell-editing/src/demos/cell-editing/CellEditingDemo.tsx
import { useState } from "react";
import {SimpleTable} from "@simple-table/react";import type { Theme, CellChangeProps } from "@simple-table/react";
import { cellEditingConfig } from "./cell-editing.demo-data";
import "@simple-table/react/styles.css";

const CellEditingDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [data, setData] = useState([...cellEditingConfig.rows]);

  const handleCellEdit = ({ accessor, newValue, row }: CellChangeProps) => {
    setData((prev) =>
      prev.map((item) =>
        item.id === row.id ? { ...item, [accessor]: newValue } : item
      )
    );
  };

  return (
    <SimpleTable
      columns={cellEditingConfig.headers}
      rows={data}
      height={height}
      theme={theme}
      onCellEdit={handleCellEdit}
    />
  );
};

export default CellEditingDemo;

// solid/cell-editing/src/demos/cell-editing/CellEditingDemo.tsx
import { createSignal } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme, CellChangeProps } from "@simple-table/solid";
import { cellEditingConfig } from "./cell-editing.demo-data";
import "@simple-table/solid/styles.css";

export default function CellEditingDemo(props: { height?: string | number; theme?: Theme }) {
  const [data, setData] = createSignal([...cellEditingConfig.rows]);

  const handleCellEdit = ({ accessor, newValue, row }: CellChangeProps) => {
    setData((prev) =>
      prev.map((item) => (item.id === row.id ? { ...item, [accessor]: newValue } : item))
    );
  };

  return (
    <SimpleTable
      columns={cellEditingConfig.headers}
      rows={data()}
      height={props.height ?? "400px"}
      theme={props.theme}
      onCellEdit={handleCellEdit}
    />
  );
}
