// packages/examples/solid/src/demos/external-filter/ExternalFilterDemo.tsx
import { createSignal, createMemo } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, TableFilterState } from "@simple-table/solid";
import {
  externalFilterConfig,
  matchesFilter,
  type FilterableEmployee,
} from "./external-filter.demo-data";
import "@simple-table/solid/styles.css";

export default function ExternalFilterDemo(props: { height?: string | number; theme?: Theme }) {
  const [filters, setFilters] = createSignal<TableFilterState<FilterableEmployee>>({});

  const filteredData = createMemo(() => {
    const entries = Object.entries(filters());
    if (entries.length === 0) return externalFilterConfig.rows;

    return externalFilterConfig.rows.filter((row) =>
      entries.every(([accessor, filter]) =>
        matchesFilter(row[accessor as keyof FilterableEmployee], filter),
      ),
    );
  });

  return (
    <SimpleTable
      columns={externalFilterConfig.headers}
      getRowId={({ row }) => row.id}
      rows={filteredData()}
      onFilterChange={setFilters}
      externalFilterHandling
      columnResizing
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}

// packages/examples/react/src/demos/external-filter/ExternalFilterDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, TableFilterState } from "@simple-table/react";
import {
  externalFilterConfig,
  matchesFilter,
  type FilterableEmployee
} from "./external-filter.demo-data";
import "@simple-table/react/styles.css";

const ExternalFilterDemo = ({
  height = "400px",
  theme
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [filters, setFilters] = useState<TableFilterState>({});

  const filteredData = useMemo(() => {
    const filterEntries = Object.entries(filters);
    if (filterEntries.length === 0) return externalFilterConfig.rows;

    return externalFilterConfig.rows.filter((row) =>
      filterEntries.every(([accessor, filter]) =>
        matchesFilter(row[accessor as keyof FilterableEmployee], filter),
      ),
    );
  }, [filters]);

  return (
    <SimpleTable
      columns={externalFilterConfig.headers}
      rows={filteredData}
      onFilterChange={setFilters}
      externalFilterHandling
      columnResizing
      height={height}
      theme={theme}
      getRowId={({ row }) => row.id}
    />
  );
};

export default ExternalFilterDemo;
