// packages/examples/angular/src/demos/billing/billing-demo.component.ts
import { Component, Input } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularHeaderObject, CellRenderer, Row, Theme } from "@simple-table/angular";
import { billingConfig } from "@simple-table/examples-shared";
import type { BillingRow } from "@simple-table/examples-shared";
import "@simple-table/angular/styles.css";

@Component({
  selector: "billing-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <simple-table
      [columnReordering]="true"
      [columnResizing]="true"
      [defaultHeaders]="headers"
      [editColumns]="true"
      [height]="height"
      [initialSortColumn]="'amount'"
      [initialSortDirection]="'desc'"
      [rowGrouping]="grouping"
      [rows]="rows"
      [selectableCells]="true"
      [theme]="theme"
      [useOddColumnBackground]="true"
    ></simple-table>
  `,
})
export class BillingDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly grouping = ["invoices", "charges"];
  readonly rows: Row[] = billingConfig.rows as unknown as Row[];

  readonly headers: AngularHeaderObject[] = billingConfig.headers.map((h) => {
    if (h.accessor === "name") {
      const nameRenderer: CellRenderer = ({ row }) => {
        const d = row as unknown as BillingRow;
        if (d.type === "account") {
          const span = document.createElement("span");
          span.style.fontWeight = "600";
          span.textContent = d.name;
          return span;
        }
        return d.name;
      };
      return { ...h, cellRenderer: nameRenderer };
    }
    return { ...h };
  });
}

// packages/examples/svelte/src/demos/billing/BillingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, HeaderObject, CellRenderer, Row } from "@simple-table/svelte";
  import { billingConfig } from "@simple-table/examples-shared";
  import type { BillingRow } from "@simple-table/examples-shared";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const nameRenderer: CellRenderer = ({ row }) => {
    const d = row as unknown as BillingRow;
    if (d.type === "account") {
      const span = document.createElement("span");
      span.style.fontWeight = "600";
      span.textContent = d.name;
      return span;
    }
    return d.name;
  };

  const headers: HeaderObject[] = billingConfig.headers.map((h) => {
    if (h.accessor === "name") {
      return { ...h, cellRenderer: nameRenderer };
    }
    return { ...h };
  });
</script>

<SimpleTable
  columnReordering={true}
  columnResizing={true}
  defaultHeaders={headers}
  editColumns={true}
  {height}
  initialSortColumn="amount"
  initialSortDirection="desc"
  rowGrouping={["invoices", "charges"]}
  rows={billingConfig.rows as unknown as Row[]}
  selectableCells={true}
  {theme}
  useOddColumnBackground={true}
/>
