// packages/examples/react/src/demos/billing/BillingDemo.tsx
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactColumnDef } from "@simple-table/react";
import { billingConfig } from "./billing.demo-data";
import type { BillingRow } from "./billing.demo-data";
import "@simple-table/react/styles.css";

const BillingDemo = ({ height = "400px", theme }: { height?: string | number; theme?: Theme }) => {
  const headers: ReactColumnDef<BillingRow>[] = billingConfig.headers.map((h) => {
    if (h.accessor === "name") {
      return {
        ...h,
        cellRenderer: ({ row }) => (
          <div className={row.type === "account" ? "font-semibold" : ""}>{row.name}</div>
        )
      };
    }
    return h;
  });

  return (
    <SimpleTable
      columnReordering
      columnResizing
      columns={headers}
      enableColumnEditor
      getRowId={({ row }) => row.id}
      height={height}
      initialSortColumn="amount"
      initialSortDirection="desc"
      rowGrouping={["invoices", "charges"]}
      rows={billingConfig.rows}
      selectableCells
      theme={theme}
      oddColumnBackground
    />
  );
};

export default BillingDemo;

// packages/examples/svelte/src/demos/billing/BillingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteColumnDef, GetRowIdParams } from "@simple-table/svelte";
  import { billingConfig } from "./billing.demo-data";
  import type { BillingRow } from "./billing.demo-data";
  import BillingNameCell from "./BillingNameCell.svelte";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const headers: SvelteColumnDef<BillingRow>[] = billingConfig.headers.map((h) => {
    if (h.accessor === "name") {
      return { ...h, cellRenderer: BillingNameCell };
    }
    return { ...h };
  });

  const getRowId = ({ row }: GetRowIdParams<BillingRow>) => row.id;
</script>

<SimpleTable
  columnReordering={true}
  columnResizing={true}
  columns={headers}
  enableColumnEditor={true}
  {getRowId}
  {height}
  initialSortColumn="amount"
  initialSortDirection="desc"
  rowGrouping={["invoices", "charges"]}
  rows={billingConfig.rows}
  selectableCells={true}
  {theme}
  oddColumnBackground={true}
/>
