// svelte/column-editing/src/demos/column-editing/ColumnEditingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, HeaderObject } from "@simple-table/svelte";
  import { columnEditingData, columnEditingHeaders } from "./column-editing.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let additionalColumns: HeaderObject[] = $state([]);
  let lastAdded = $state("");

  function addColumn() {
    const n = additionalColumns.length + 1;
    const col: HeaderObject = { accessor: `custom-${n}`, label: `Custom ${n}`, width: 120, type: "string" };
    additionalColumns = [...additionalColumns, col];
    lastAdded = col.label;
  }

  function handleHeaderEdit(_header: HeaderObject, newLabel: string) {
    lastAdded = `Renamed to: ${newLabel}`;
  }

  let headers = $derived([...columnEditingHeaders, ...additionalColumns]);
</script>

<div>
  <div style="margin-bottom: 12px">
    <button
      onclick={addColumn}
      style="background-color: #007bff; color: white; border: none; padding: 6px 14px; border-radius: 4px; cursor: pointer; font-size: 13px;"
    >
      + Add Column
    </button>
    {#if lastAdded}
      <span style="margin-left: 12px; color: #64748b; font-size: 13px;">Added: {lastAdded}</span>
    {/if}
  </div>
  <SimpleTable
    defaultHeaders={headers}
    rows={columnEditingData}
    {height}
    {theme}
    enableHeaderEditing={true}
    selectableColumns={true}
    onHeaderEdit={handleHeaderEdit}
  />
</div>

// solid/column-editing/src/demos/column-editing/ColumnEditingDemo.tsx
import { createSignal, createMemo } from "solid-js";
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/solid";
import type { Theme, HeaderObject, SolidHeaderObject } from "@simple-table/solid";
import { columnEditingData, columnEditingHeaders } from "./column-editing.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnEditingDemo(props: { height?: string | number; theme?: Theme }) {
  const [additionalColumns, setAdditionalColumns] = createSignal<SolidHeaderObject[]>([]);
  const [lastAdded, setLastAdded] = createSignal("");

  const addColumn = () => {
    const n = additionalColumns().length + 1;
    const col: SolidHeaderObject = { accessor: `custom-${n}`, label: `Custom ${n}`, width: 120, type: "string" };
    setAdditionalColumns([...additionalColumns(), col]);
    setLastAdded(col.label);
  };

  const headers = createMemo(() => [...defaultHeadersFromCore(columnEditingHeaders), ...additionalColumns()]);

  return (
    <div>
      <div style={{ "margin-bottom": "12px" }}>
        <button
          type="button"
          onClick={addColumn}
          style={{
            "background-color": "#007bff",
            color: "white",
            border: "none",
            padding: "6px 14px",
            "border-radius": "4px",
            cursor: "pointer",
            "font-size": "13px",
          }}
        >
          + Add Column
        </button>
        {lastAdded() && (
          <span style={{ "margin-left": "12px", color: "#64748b", "font-size": "13px" }}>Added: {lastAdded()}</span>
        )}
      </div>
      <SimpleTable
        defaultHeaders={headers()}
        rows={columnEditingData}
        height={props.height ?? "400px"}
        theme={props.theme}
        enableHeaderEditing
        selectableColumns
        onHeaderEdit={(_header, newLabel) => setLastAdded(`Renamed to: ${newLabel}`)}
      />
    </div>
  );
}
