// packages/examples/svelte/src/demos/music/MusicArtistTypeCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getMusicThemeColors } from "./music.demo-data";
  import type { MusicArtist } from "./music.demo-data";

  let { row, theme }: CellRendererProps<MusicArtist> = $props();
  const c = $derived(getMusicThemeColors(theme));
</script>

<div style="display:flex;flex-direction:column;gap:4px;">
  <div style="font-size:13px;color:{c.gray};">{row.artistType}, {row.pronouns}</div>
  <div style="font-size:12px;color:{c.gray};">{row.recordLabel}</div>
  <div style="font-size:12px;color:{c.gray};">Lyrics Language: {row.lyricsLanguage}</div>
</div>

// packages/examples/angular/src/demos/music/music-artist-type-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Theme } from "@simple-table/angular";
import { getMusicThemeColors } from "./music.demo-data";
import type { MusicArtist } from "./music.demo-data";

@Component({
  standalone: true,
  selector: "demo-music-artist-type",
  template: `
    <div style="display:flex;flex-direction:column;gap:4px;">
      <div style="font-size:13px;" [style.color]="c.gray">{{ row.artistType }}, {{ row.pronouns }}</div>
      <div style="font-size:12px;" [style.color]="c.gray">{{ row.recordLabel }}</div>
      <div style="font-size:12px;" [style.color]="c.gray">Lyrics Language: {{ row.lyricsLanguage }}</div>
    </div>
  `,
})
export class MusicArtistTypeCellComponent {
  @Input({ required: true }) row!: MusicArtist;
  @Input() theme?: Theme;

  get c(): Record<string, string> {
    return getMusicThemeColors(this.theme);
  }
}
