// svelte/music/src/demos/music/MusicPlaylistCountCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getMusicThemeColors } from "./music.demo-data";
  import type { MusicArtist } from "./music.demo-data";
  import MusicTag from "./MusicTag.svelte";

  let { row, theme }: CellRendererProps<MusicArtist> = $props();
  const c = $derived(getMusicThemeColors(theme));
  const tagText = $derived(
    `↑ +${row.playlistCountGrowth} (${row.playlistCountGrowthPercent.toFixed(2)}%)`,
  );
</script>

<div style="display:flex;flex-direction:column;gap:4px;align-items:flex-start;">
  <div style="font-size:14px;color:{c.gray};">{row.playlistCount.toLocaleString()}</div>
  <MusicTag text={tagText} variant="green" c={c} />
</div>

// packages/examples/angular/src/demos/music/music-playlist-count-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Theme } from "@simple-table/angular";
import { getMusicThemeColors, musicNumber } from "./music.demo-data";
import type { MusicArtist } from "./music.demo-data";
import { MusicTagComponent } from "./music-tag.component";

@Component({
  standalone: true,
  selector: "demo-music-playlist-count",
  imports: [MusicTagComponent],
  template: `
    <div style="display:flex;flex-direction:column;gap:4px;align-items:flex-start;">
      <div style="font-size:14px;" [style.color]="c.gray">{{ row.playlistCount.toLocaleString() }}</div>
      <demo-music-tag [text]="tagText" variant="green" [theme]="theme" />
    </div>
  `,
})
export class MusicPlaylistCountCellComponent {
  @Input({ required: true }) row!: MusicArtist;
  @Input() theme?: Theme;

  get c(): Record<string, string> {
    return getMusicThemeColors(this.theme);
  }

  get tagText(): string {
    return `↑ +${this.row.playlistCountGrowth} (${musicNumber(this.row, "playlistCountGrowthPercent").toFixed(2)}%)`;
  }
}
