// react/value-formatter/src/demos/value-formatter/ValueFormatterDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { valueFormatterConfig } from "./value-formatter.demo-data";
import "@simple-table/react/styles.css";

const ValueFormatterDemo = ({
  height = "400px",
  theme
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      columns={valueFormatterConfig.headers}
      rows={valueFormatterConfig.rows}
      height={height}
      theme={theme}
      selectableCells={valueFormatterConfig.tableProps.selectableCells}
      getRowId={({ row }) => row.id}
    />
  );
};

export default ValueFormatterDemo;

// svelte/value-formatter/src/demos/value-formatter/ValueFormatterDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { valueFormatterConfig } from "./value-formatter.demo-data";
  import type { FormattedEmployee } from "./value-formatter.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const getRowId = ({ row }: GetRowIdParams<FormattedEmployee>) => row.id;
</script>

<SimpleTable
  columns={valueFormatterConfig.headers}
  rows={valueFormatterConfig.rows}
  getRowId={getRowId}
  {height}
  {theme}
  selectableCells={valueFormatterConfig.tableProps.selectableCells}
/>
