// solid/value-formatter/src/demos/value-formatter/ValueFormatterDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { valueFormatterConfig } from "./value-formatter.demo-data";
import "@simple-table/solid/styles.css";

export default function ValueFormatterDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(valueFormatterConfig.headers)}
      rows={valueFormatterConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      selectableCells={valueFormatterConfig.tableProps.selectableCells}
    />
  );
}

// svelte/value-formatter/src/demos/value-formatter/ValueFormatterDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { valueFormatterConfig } from "./value-formatter.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(valueFormatterConfig.headers)}
  rows={valueFormatterConfig.rows}
  {height}
  {theme}
  selectableCells={valueFormatterConfig.tableProps.selectableCells}
/>
