// svelte/aggregate-functions/src/demos/aggregate-functions/AggregateFunctionsDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(aggregateFunctionsConfig.headers)}
  rows={aggregateFunctionsConfig.rows}
  rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
  columnResizing={true}
  {height}
  {theme}
/>

// packages/examples/react/src/demos/aggregate-functions/AggregateFunctionsDemo.tsx
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
import "@simple-table/react/styles.css";

const AggregateFunctionsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(aggregateFunctionsConfig.headers)}
      rows={aggregateFunctionsConfig.rows}
      rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
      columnResizing
      height={height}
      theme={theme}
    />
  );
};

export default AggregateFunctionsDemo;
