// svelte/quick-start/src/demos/quick-start/QuickStartDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { quickStartConfig } from "./quick-start.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "300px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(quickStartConfig.headers)}
  rows={quickStartConfig.rows}
  {height}
  {theme}
  editColumns={quickStartConfig.tableProps.editColumns}
  selectableCells={quickStartConfig.tableProps.selectableCells}
  customTheme={quickStartConfig.tableProps.customTheme}
/>

// solid/quick-start/src/demos/quick-start/QuickStartDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { quickStartConfig } from "./quick-start.demo-data";
import "@simple-table/solid/styles.css";

export default function QuickStartDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(quickStartConfig.headers)}
      rows={quickStartConfig.rows}
      height={props.height ?? "300px"}
      theme={props.theme}
      editColumns={quickStartConfig.tableProps.editColumns}
      selectableCells={quickStartConfig.tableProps.selectableCells}
      customTheme={quickStartConfig.tableProps.customTheme}
    />
  );
}
