// vue/empty-state/src/demos/empty-state/EmptyStateDemo.vue
<script setup lang="ts">
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/vue";
import type { Theme } from "@simple-table/vue";
import { emptyStateConfig, buildEmptyStateElement } from "./empty-state.demo-data";
import "@simple-table/vue/styles.css";

const props = withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const emptyState = buildEmptyStateElement();
</script>

<template>
  <SimpleTable
    :default-headers="defaultHeadersFromCore(emptyStateConfig.headers)"
    :rows="emptyStateConfig.rows"
    :table-empty-state-renderer="emptyState"
    :height="props.height"
    :theme="props.theme"
  />
</template>

// packages/examples/svelte/src/demos/empty-state/EmptyStateDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { emptyStateConfig, buildEmptyStateElement } from "./empty-state.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const emptyState = buildEmptyStateElement();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(emptyStateConfig.headers)}
  rows={emptyStateConfig.rows}
  tableEmptyStateRenderer={emptyState}
  {height}
  {theme}
/>
