// vue/column-visibility/src/demos/column-visibility/MarketingColumnEditorRow.vue
<script setup lang="ts">
import type { ColumnEditorRowRendererProps } from "@simple-table/vue";
import { ref, watchEffect } from "vue";

const props = defineProps<ColumnEditorRowRendererProps>();

const anchorRef = ref<HTMLDivElement | null>(null);

function appendMarketingColumnEditorSlot(parent: HTMLElement, slot: string | Node | undefined): void {
  if (slot == null) return;
  if (typeof slot === "string") {
    parent.appendChild(document.createTextNode(slot));
  } else {
    parent.appendChild(slot);
  }
}

/** Vue examples-only copy of the marketing column-editor row layout. */
function buildMarketingStyleColumnEditorRow(rootProps: ColumnEditorRowRendererProps): HTMLElement {
  const { components } = rootProps;
  const outer = document.createElement("div");
  outer.style.width = "100%";
  outer.style.display = "flex";
  outer.style.alignItems = "center";
  outer.style.justifyContent = "space-between";
  outer.style.gap = "8px";
  outer.style.paddingRight = "8px";

  const left = document.createElement("div");
  left.style.display = "flex";
  left.style.alignItems = "center";
  left.style.gap = "8px";
  appendMarketingColumnEditorSlot(left, components.expandIcon as Node | string | undefined);
  appendMarketingColumnEditorSlot(left, components.checkbox as Node | string | undefined);
  appendMarketingColumnEditorSlot(left, components.labelContent as Node | string | undefined);
  outer.appendChild(left);

  const right = document.createElement("div");
  appendMarketingColumnEditorSlot(right, components.dragIcon as Node | string | undefined);
  outer.appendChild(right);

  return outer;
}

watchEffect(() => {
  const el = anchorRef.value;
  if (!el) return;
  el.replaceChildren(buildMarketingStyleColumnEditorRow(props));
});
</script>

<template>
  <div ref="anchorRef" style="display: contents" />
</template>

// angular/column-visibility/src/demos/column-visibility/marketing-column-editor-row.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  ViewChild,
} from "@angular/core";
import type { ColumnEditorRowRendererProps } from "@simple-table/angular";

function attach(slot: unknown, host: HTMLElement | undefined): void {
  if (!host) return;
  host.replaceChildren();
  if (slot == null) return;
  if (typeof slot === "string") {
    host.textContent = slot;
  } else if (slot instanceof Node) {
    host.appendChild(slot);
  }
}

/** Marketing-style column-editor row; slots are framework-provided nodes or strings. */
@Component({
  selector: "st-examples-marketing-column-editor-row",
  standalone: true,
  template: `
    <div
      style="width:100%;display:flex;align-items:center;justify-content:space-between;gap:8px;padding-right:8px;"
    >
      <div style="display:flex;align-items:center;gap:8px;">
        <span #expandHost></span>
        <span #checkboxHost></span>
        <span #labelHost></span>
      </div>
      <span #dragHost></span>
    </div>
  `,
})
export class MarketingColumnEditorRowComponent implements AfterViewInit, OnChanges {
  @Input({ required: true }) accessor!: ColumnEditorRowRendererProps["accessor"];
  @Input({ required: true }) header!: ColumnEditorRowRendererProps["header"];
  @Input({ required: true }) components!: ColumnEditorRowRendererProps["components"];
  @Input() panelSection?: ColumnEditorRowRendererProps["panelSection"];
  @Input() essential?: ColumnEditorRowRendererProps["essential"];
  @Input() canToggleVisibility?: ColumnEditorRowRendererProps["canToggleVisibility"];
  @Input() allowColumnPinning?: ColumnEditorRowRendererProps["allowColumnPinning"];
  @Input() pinControl?: ColumnEditorRowRendererProps["pinControl"];

  @ViewChild("expandHost") expandRef?: ElementRef<HTMLSpanElement>;
  @ViewChild("checkboxHost") checkboxRef?: ElementRef<HTMLSpanElement>;
  @ViewChild("labelHost") labelRef?: ElementRef<HTMLSpanElement>;
  @ViewChild("dragHost") dragRef?: ElementRef<HTMLSpanElement>;

  ngAfterViewInit(): void {
    this.syncSlots();
  }

  ngOnChanges(): void {
    this.syncSlots();
  }

  private syncSlots(): void {
    const c = this.components;
    attach(c.expandIcon, this.expandRef?.nativeElement);
    attach(c.checkbox, this.checkboxRef?.nativeElement);
    attach(c.labelContent, this.labelRef?.nativeElement);
    attach(c.dragIcon, this.dragRef?.nativeElement);
  }
}
