// svelte/row-height/src/demos/row-height/RowHeightDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { rowHeightConfig } from "./row-height.demo-data";
  import type { ArchitectStaff } from "./row-height.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const getRowId = ({ row }: GetRowIdParams<ArchitectStaff>) => row.id;
</script>

<SimpleTable
  columns={rowHeightConfig.headers}
  rows={rowHeightConfig.rows}
  getRowId={getRowId}
  {height}
  {theme}
  customTheme={rowHeightConfig.tableProps.customTheme}
/>

// packages/examples/react/src/demos/row-height/RowHeightDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { rowHeightConfig, type ArchitectStaff } from "./row-height.demo-data";
import "@simple-table/react/styles.css";

const RowHeightDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable<ArchitectStaff>
      columns={rowHeightConfig.headers}
      rows={rowHeightConfig.rows}
      height={height}
      theme={theme}
      customTheme={rowHeightConfig.tableProps.customTheme}
      getRowId={({ row }) => row.id}
    />
  );
};

export default RowHeightDemo;
