// packages/examples/angular/src/demos/crm/crm-time-ago-cell.component.ts
import { Component, Input } from "@angular/core";
import type {  } from "@simple-table/angular";
import type { CRMLead } from "./crm.demo-data";
import { crmCellPalette } from "./crm-demo-context";

@Component({
  standalone: true,
  selector: "demo-crm-time-ago",
  template: `<div style="font-size:13px;" [style.color]="palette().textSecondary">{{ row.timeAgo }}</div>`,
})
export class CrmTimeAgoCellComponent {
  @Input({ required: true }) row!: CRMLead;

  protected readonly palette = crmCellPalette;
}

// svelte/crm/src/demos/crm/CrmTimeAgoCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { CRMLead } from "./crm.demo-data";
  import { crmCellColors } from "./crm-demo-stores";

  let { row }: CellRendererProps<CRMLead> = $props();
  const colors = $derived($crmCellColors);
</script>

<div style="font-size:13px;color:{colors.textSecondary};">{row.timeAgo}</div>
