// packages/examples/svelte/src/demos/window-infinite-scroll/WindowInfiniteScrollDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import {
    generateWindowScrollRows,
    windowScrollHeaders,
  } from "./window-infinite-scroll.demo-data";
  import type { WindowScrollEmployee } from "./window-infinite-scroll.demo-data";
  import "@simple-table/svelte/styles.css";

  // `height` is intentionally ignored — this demo is about *not* setting one.
  let { theme }: { height?: string | number; theme?: Theme } = $props();

  const INITIAL_ROWS = 50;
  const BATCH_SIZE = 50;
  const MAX_ROWS = 5_000;
  const LOAD_DELAY_MS = 350;

  let wrapper: HTMLDivElement | undefined = $state();
  let rows = $state<WindowScrollEmployee[]>(generateWindowScrollRows(0, INITIAL_ROWS));
  let loading = $state(false);
  let hasMore = $state(true);

  let statusLabel = $derived(
    loading
      ? "Loading more rows…"
      : hasMore
        ? `${rows.length.toLocaleString()} rows loaded · scroll for more`
        : `${rows.length.toLocaleString()} rows loaded · end of dataset`,
  );

  const getScrollParent = () => wrapper?.parentElement ?? null;
  const getRowId = ({ row }: GetRowIdParams<WindowScrollEmployee>) => row.id;

  function handleLoadMore() {
    if (loading || !hasMore) return;
    loading = true;

    setTimeout(() => {
      const next = generateWindowScrollRows(rows.length, BATCH_SIZE);
      const updated = [...rows, ...next];
      if (updated.length >= MAX_ROWS) {
        hasMore = false;
        rows = updated.slice(0, MAX_ROWS);
      } else {
        rows = updated;
      }
      loading = false;
    }, LOAD_DELAY_MS);
  }
</script>

<div bind:this={wrapper} style="max-width: 1100px; margin: 0 auto">
  <h1 style="font-size: 28px; margin: 0 0 12px 0; color: #0f172a">
    Window-Scroll Infinite Loading
  </h1>
  <p
    style="font-size: 15px; line-height: 1.6; color: #475569; margin: 0 0 16px 0"
  >
    This table has no <code>height</code> or <code>maxHeight</code>. It grows to its natural
    size inside the page, and uses the outer scroll container (<code>scrollParent</code>) to
    drive both row virtualization and <code>onLoadMore</code>. The header pins to the top of
    the outer scroll viewport as you scroll. Scroll down — new rows stream in as you approach
    the bottom.
  </p>

  <div
    style="display: inline-flex; align-items: center; gap: 8px; padding: 6px 12px; margin-bottom: 16px; background: #eef2ff; color: #3730a3; border-radius: 999px; font-size: 13px; font-weight: 500"
  >
    <span
      style="display: inline-block; width: 8px; height: 8px; border-radius: 50%; background: #6366f1"
    ></span>
    <span>{statusLabel}</span>
  </div>

  <SimpleTable
    columns={windowScrollHeaders}
    {rows}
    {theme}
    {getRowId}
    scrollParent={getScrollParent}
    infiniteScrollThreshold={400}
    onLoadMore={handleLoadMore}
    isLoading={loading && rows.length === 0}
  />

  <p
    style="font-size: 13px; color: #94a3b8; margin: 24px 0 48px 0; text-align: center"
  >
    End of demo content. Keep scrolling near the bottom and onLoadMore will keep firing until
    the dataset is exhausted.
  </p>
</div>

// packages/examples/solid/src/demos/window-infinite-scroll/WindowInfiniteScrollDemo.tsx
import { createMemo, createSignal } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import {
  generateWindowScrollRows,
  windowScrollHeaders,
  type WindowScrollEmployee,
} from "./window-infinite-scroll.demo-data";
import "@simple-table/solid/styles.css";

const INITIAL_ROWS = 50;
const BATCH_SIZE = 50;
const MAX_ROWS = 5_000;
const LOAD_DELAY_MS = 350;

export default function WindowInfiniteScrollDemo(_props: {
  height?: string | number;
  theme?: Theme;
}) {
  let wrapperRef: HTMLDivElement | undefined;

  const [rows, setRows] = createSignal<WindowScrollEmployee[]>(
    generateWindowScrollRows(0, INITIAL_ROWS),
  );
  const [loading, setLoading] = createSignal(false);
  const [hasMore, setHasMore] = createSignal(true);

  const statusLabel = createMemo(() => {
    if (loading()) return "Loading more rows…";
    if (hasMore()) {
      return `${rows().length.toLocaleString()} rows loaded · scroll for more`;
    }
    return `${rows().length.toLocaleString()} rows loaded · end of dataset`;
  });

  const getScrollParent = () => wrapperRef?.parentElement ?? null;

  const handleLoadMore = () => {
    if (loading() || !hasMore()) return;
    setLoading(true);

    setTimeout(() => {
      setRows((prev) => {
        const next = generateWindowScrollRows(prev.length, BATCH_SIZE);
        const updated = [...prev, ...next];
        if (updated.length >= MAX_ROWS) {
          setHasMore(false);
          return updated.slice(0, MAX_ROWS);
        }
        return updated;
      });
      setLoading(false);
    }, LOAD_DELAY_MS);
  };

  return (
    <div ref={wrapperRef} style={{ "max-width": "1100px", margin: "0 auto" }}>
      <h1 style={{ "font-size": "28px", margin: "0 0 12px 0", color: "#0f172a" }}>
        Window-Scroll Infinite Loading
      </h1>
      <p
        style={{
          "font-size": "15px",
          "line-height": "1.6",
          color: "#475569",
          margin: "0 0 16px 0",
        }}
      >
        This table has no <code>height</code> or <code>maxHeight</code>. It grows to its natural
        size inside the page, and uses the outer scroll container (<code>scrollParent</code>) to
        drive both row virtualization and <code>onLoadMore</code>. The header pins to the top of
        the outer scroll viewport as you scroll. Scroll down — new rows stream in as you approach
        the bottom.
      </p>

      <div
        style={{
          display: "inline-flex",
          "align-items": "center",
          gap: "8px",
          padding: "6px 12px",
          "margin-bottom": "16px",
          background: "#eef2ff",
          color: "#3730a3",
          "border-radius": "999px",
          "font-size": "13px",
          "font-weight": "500",
        }}
      >
        <span
          style={{
            display: "inline-block",
            width: "8px",
            height: "8px",
            "border-radius": "50%",
            background: "#6366f1",
          }}
        />
        <span>{statusLabel()}</span>
      </div>

      <SimpleTable
        columns={windowScrollHeaders}
        rows={rows()}
        theme={_props.theme}
        getRowId={({ row }) => String(row.id)}
        scrollParent={getScrollParent}
        infiniteScrollThreshold={400}
        onLoadMore={handleLoadMore}
        isLoading={loading() && rows().length === 0}
      />

      <p
        style={{
          "font-size": "13px",
          color: "#94a3b8",
          margin: "24px 0 48px 0",
          "text-align": "center",
        }}
      >
        End of demo content. Keep scrolling near the bottom and onLoadMore will keep firing until
        the dataset is exhausted.
      </p>
    </div>
  );
}
