// packages/examples/angular/src/demos/spreadsheet/spreadsheet-demo.component.ts
import { Component, Input, ViewChild } from "@angular/core";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularHeaderObject, CellChangeProps, HeaderObject, HeaderRenderer, Theme } from "@simple-table/angular";
import { spreadsheetConfig, recalculateAmortization } from "@simple-table/examples-shared";
import type { SpreadsheetRow } from "@simple-table/examples-shared";
import "@simple-table/angular/styles.css";
import "../../../../shared/src/styles/spreadsheet-custom.css";

@Component({
  selector: "spreadsheet-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div class="spreadsheet-container">
      <simple-table
        #simpleTable
        [defaultHeaders]="headers"
        [rows]="data"
        [height]="height"
        [theme]="theme"
        [columnBorders]="true"
        [columnReordering]="true"
        [columnResizing]="true"
        [enableHeaderEditing]="true"
        [enableRowSelection]="true"
        [selectableCells]="true"
        [selectableColumns]="true"
        [useOddEvenRowBackground]="true"
        [customTheme]="{ rowHeight: 22 }"
        (cellEdit)="onCellEdit($event)"
      ></simple-table>
    </div>
  `,
})
export class SpreadsheetDemoComponent {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  data = [...spreadsheetConfig.rows];
  private additionalColumns: HeaderObject[] = [];

  get headers(): AngularHeaderObject[] {
    return this.buildHeaders();
  }

  private buildHeaders(): AngularHeaderObject[] {
    const baseHeaders: HeaderObject[] = [...spreadsheetConfig.headers];
    const addColumnHeaderRenderer: HeaderRenderer = () => {
      const div = document.createElement("div");
      div.style.display = "flex";
      div.style.justifyContent = "center";

      const btn = document.createElement("button");
      btn.textContent = "+ Add Column";
      Object.assign(btn.style, {
        color: "white",
        border: "none",
        padding: "4px 10px",
        borderRadius: "4px",
        cursor: "pointer",
        fontSize: "11px",
        fontWeight: "500",
        whiteSpace: "nowrap",
      } satisfies Partial<CSSStyleDeclaration>);

      btn.addEventListener("click", () => {
        const totalCols = spreadsheetConfig.headers.length + this.additionalColumns.length;
        const newCol: HeaderObject = {
          accessor: `column${totalCols + 1}`,
          label: `Column ${totalCols + 1}`,
          width: 120,
          minWidth: 80,
          type: "number",
          align: "right",
          isEditable: true,
          aggregation: { type: "sum" },
        };
        this.additionalColumns = [...this.additionalColumns, newCol];
        this.tableRef?.getAPI()?.updateHeaders(this.buildHeaders() as any);
      });

      div.appendChild(btn);
      return div;
    };

    return [
      ...baseHeaders,
      ...this.additionalColumns,
      {
        accessor: "actions",
        label: "",
        width: 100,
        minWidth: 100,
        filterable: false,
        type: "other" as const,
        disableReorder: true,
        headerRenderer: addColumnHeaderRenderer as any,
      },
    ] as AngularHeaderObject[];
  }

  onCellEdit({ accessor, newValue, row }: CellChangeProps): void {
    this.data = this.data.map((item) => {
      if (item.id === row.id) {
        return recalculateAmortization(item as SpreadsheetRow, accessor, newValue as string | number);
      }
      return item;
    });
  }
}

// packages/examples/svelte/src/demos/spreadsheet/SpreadsheetDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, HeaderObject, CellChangeProps } from "@simple-table/svelte";
  import { spreadsheetConfig, recalculateAmortization } from "@simple-table/examples-shared";
  import type { SpreadsheetRow } from "@simple-table/examples-shared";
  import "@simple-table/svelte/styles.css";
  import "@simple-table/examples-shared/styles/spreadsheet-custom.css";

  let { height = "400px", theme = "light" as Theme }: { height?: string | number; theme?: Theme } = $props();

  let data = $state([...spreadsheetConfig.rows]);
  let additionalColumns = $state<HeaderObject[]>([]);
  let tableRef: any;

  const headers = $derived.by((): HeaderObject[] => {
    const baseHeaders: HeaderObject[] = [...spreadsheetConfig.headers];
    return [
      ...baseHeaders,
      ...additionalColumns,
      {
        accessor: "actions",
        label: "",
        width: 100,
        minWidth: 100,
        filterable: false,
        type: "other" as const,
        disableReorder: true,
        headerRenderer: () => {
          const div = document.createElement("div");
          div.style.display = "flex";
          div.style.justifyContent = "center";

          const btn = document.createElement("button");
          btn.textContent = "+ Add Column";
          Object.assign(btn.style, {
            color: "white",
            border: "none",
            padding: "4px 10px",
            borderRadius: "4px",
            cursor: "pointer",
            fontSize: "11px",
            fontWeight: "500",
            whiteSpace: "nowrap",
          } satisfies Partial<CSSStyleDeclaration>);

          btn.addEventListener("click", () => {
            const totalCols = spreadsheetConfig.headers.length + additionalColumns.length;
            const newCol: HeaderObject = {
              accessor: `column${totalCols + 1}`,
              label: `Column ${totalCols + 1}`,
              width: 120,
              minWidth: 80,
              type: "number",
              align: "right",
              isEditable: true,
              aggregation: { type: "sum" },
            };
            additionalColumns = [...additionalColumns, newCol];
          });

          div.appendChild(btn);
          return div;
        },
      },
    ];
  });

  function handleCellEdit({ accessor, newValue, row }: CellChangeProps) {
    data = data.map((item) => {
      if (item.id === row.id) {
        return recalculateAmortization(item as SpreadsheetRow, accessor, newValue as string | number);
      }
      return item;
    });
  }
</script>

<div class="spreadsheet-container">
  <SimpleTable
    bind:this={tableRef}
    columnBorders={true}
    columnReordering={true}
    columnResizing={true}
    defaultHeaders={headers}
    enableHeaderEditing={true}
    enableRowSelection={true}
    {height}
    onCellEdit={handleCellEdit}
    customTheme={{ rowHeight: 22 }}
    rows={data}
    selectableCells={true}
    selectableColumns={true}
    {theme}
    useOddEvenRowBackground={true}
  />
</div>
