// solid/spreadsheet/src/demos/spreadsheet/SpreadsheetDemo.tsx
import { createSignal, createMemo } from "solid-js";
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/solid";
import type { Theme, SolidHeaderObject, CellChangeProps } from "@simple-table/solid";
import { spreadsheetConfig, recalculateAmortization } from "./spreadsheet.demo-data";
import type { SpreadsheetRow } from "./spreadsheet.demo-data";
import "@simple-table/solid/styles.css";
import "./spreadsheet-custom.css";

export default function SpreadsheetDemo(props: { height?: string | number; theme?: Theme }) {
  const theme = () => props.theme ?? "light";
  const [data, setData] = createSignal([...spreadsheetConfig.rows]);
  const [additionalColumns, setAdditionalColumns] = createSignal<SolidHeaderObject[]>([]);

  const headers = createMemo((): SolidHeaderObject[] => {
    const baseHeaders = defaultHeadersFromCore(spreadsheetConfig.headers);
    return [
      ...baseHeaders,
      ...additionalColumns(),
      {
        accessor: "actions",
        label: "",
        width: 100,
        minWidth: 100,
        filterable: false,
        type: "other" as const,
        disableReorder: true,
        headerRenderer: () => (
          <div style={{ display: "flex", "justify-content": "center" }}>
            <button
              onClick={() => {
                const newCol: SolidHeaderObject = {
                  accessor: `column${baseHeaders.length + additionalColumns().length + 1}`,
                  label: `Column ${baseHeaders.length + additionalColumns().length + 1}`,
                  width: 120,
                  minWidth: 80,
                  type: "number",
                  align: "right",
                  isEditable: true,
                  aggregation: { type: "sum" },
                };
                setAdditionalColumns([...additionalColumns(), newCol]);
              }}
              style={{ color: "white", border: "none", padding: "4px 10px", "border-radius": "4px", cursor: "pointer", "font-size": "11px", "font-weight": "500", "white-space": "nowrap" }}
            >
              + Add Column
            </button>
          </div>
        ),
      },
    ];
  });

  const handleCellEdit = ({ accessor, newValue, row }: CellChangeProps) => {
    setData((prev) =>
      prev.map((item) => {
        if (item.id === row.id) {
          return recalculateAmortization(item as SpreadsheetRow, accessor, newValue as string | number);
        }
        return item;
      })
    );
  };

  return (
    <div class="spreadsheet-container">
      <SimpleTable
        columnBorders
        columnReordering
        columnResizing
        defaultHeaders={headers()}
        enableHeaderEditing
        enableRowSelection
        height={props.height ?? "400px"}
        onCellEdit={handleCellEdit}
        customTheme={{ rowHeight: 22 }}
        rows={data()}
        selectableCells
        selectableColumns
        theme={theme()}
        useOddEvenRowBackground
      />
    </div>
  );
}

// react/spreadsheet/src/demos/spreadsheet/SpreadsheetDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/react";
import type { Theme, ReactHeaderObject, CellChangeProps } from "@simple-table/react";
import { spreadsheetConfig, recalculateAmortization } from "./spreadsheet.demo-data";
import "@simple-table/react/styles.css";
import "./spreadsheet-custom.css";

const SpreadsheetDemo = ({ height = "400px", theme = "light" }: { height?: string | number; theme?: Theme }) => {
  const [data, setData] = useState([...spreadsheetConfig.rows]);
  const [additionalColumns, setAdditionalColumns] = useState<ReactHeaderObject[]>([]);

  const headers = useMemo((): ReactHeaderObject[] => {
    const baseHeaders = defaultHeadersFromCore(spreadsheetConfig.headers);
    return [
      ...baseHeaders,
      ...additionalColumns,
      {
        accessor: "actions",
        label: "",
        width: 100,
        minWidth: 100,
        filterable: false,
        type: "other" as const,
        disableReorder: true,
        headerRenderer: () => (
          <div style={{ display: "flex", justifyContent: "center" }}>
            <button
              onClick={() => {
                const newCol: ReactHeaderObject = {
                  accessor: `column${baseHeaders.length + additionalColumns.length + 1}`,
                  label: `Column ${baseHeaders.length + additionalColumns.length + 1}`,
                  width: 120,
                  minWidth: 80,
                  type: "number",
                  align: "right",
                  isEditable: true,
                  aggregation: { type: "sum" },
                };
                setAdditionalColumns([...additionalColumns, newCol]);
              }}
              style={{ color: "white", border: "none", padding: "4px 10px", borderRadius: "4px", cursor: "pointer", fontSize: "11px", fontWeight: 500, whiteSpace: "nowrap" }}
            >
              + Add Column
            </button>
          </div>
        ),
      },
    ];
  }, [additionalColumns]);

  const handleCellEdit = ({ accessor, newValue, row }: CellChangeProps) => {
    setData((prev) =>
      prev.map((item) => {
        if (item.id === row.id) {
          const val = typeof newValue === "number" ? newValue : String(newValue ?? "");
          return recalculateAmortization(item, accessor, val);
        }
        return item;
      })
    );
  };

  return (
    <div className="spreadsheet-container">
      <SimpleTable
        columnBorders
        columnReordering
        columnResizing
        defaultHeaders={headers}
        enableHeaderEditing
        enableRowSelection
        height={height}
        onCellEdit={handleCellEdit}
        customTheme={{ rowHeight: 22 }}
        rows={data}
        selectableCells
        selectableColumns
        theme={theme}
        useOddEvenRowBackground
      />
    </div>
  );
};

export default SpreadsheetDemo;
