// packages/examples/react/src/demos/animations/AnimationsDemo.tsx
import { useState } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactColumnDef } from "@simple-table/react";
import { animationsConfig } from "./animations.demo-data";
import "@simple-table/react/styles.css";

const AnimationsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [headers, setHeaders] = useState(() => [...animationsConfig.headers]);

  const handleColumnOrderChange = (newHeaders: ReactColumnDef[]) => {
    setHeaders(newHeaders);
  };

  return (
    <SimpleTable
      columnReordering={animationsConfig.tableProps.columnReordering}
      columns={headers}
      enableColumnEditor={animationsConfig.tableProps.enableColumnEditor}
      enableColumnEditorInitOpen={animationsConfig.tableProps.enableColumnEditorInitOpen}
      rows={animationsConfig.rows}
      height={height}
      theme={theme}
      onColumnOrderChange={handleColumnOrderChange}
    />
  );
};

export default AnimationsDemo;

// packages/examples/svelte/src/demos/animations/AnimationsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteColumnDef } from "@simple-table/svelte";
  import { animationsConfig } from "./animations.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let headers: SvelteColumnDef[] = $state([...animationsConfig.headers]);

  function handleColumnOrderChange(newHeaders: SvelteColumnDef[]) {
    headers = newHeaders;
  }
</script>

<SimpleTable
  columnReordering
  columns={headers}
  enableColumnEditor
  enableColumnEditorInitOpen
  rows={animationsConfig.rows}
  {height}
  {theme}
  onColumnOrderChange={handleColumnOrderChange}
/>
