// react/column-width/src/demos/column-width/ColumnWidthDemo.tsx
import { useState, useEffect } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { columnWidthConfig } from "./column-width.demo-data";
import "@simple-table/react/styles.css";

const ColumnWidthDemo = ({
  height = "400px",
  theme
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const check = () => setIsMobile(window.innerWidth < 768);
    check();
    window.addEventListener("resize", check);
    return () => window.removeEventListener("resize", check);
  }, []);

  return (
    <SimpleTable
      autoExpandColumns={!isMobile}
      columnResizing
      columns={columnWidthConfig.headers}
      height={height}
      rows={columnWidthConfig.rows}
      theme={theme}
      getRowId={({ row }) => row.id}
    />
  );
};

export default ColumnWidthDemo;

// solid/column-width/src/demos/column-width/ColumnWidthDemo.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnWidthConfig } from "./column-width.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnWidthDemo(props: { height?: string | number; theme?: Theme }) {
  const [isMobile, setIsMobile] = createSignal(false);

  const check = () => setIsMobile(window.innerWidth < 768);

  onMount(() => {
    check();
    window.addEventListener("resize", check);
  });

  onCleanup(() => {
    window.removeEventListener("resize", check);
  });

  return (
    <SimpleTable
      autoExpandColumns={!isMobile()}
      columnResizing
      columns={columnWidthConfig.headers}
      getRowId={({ row }) => row.id}
      height={props.height ?? "400px"}
      rows={columnWidthConfig.rows}
      theme={props.theme}
    />
  );
}
