// packages/examples/svelte/src/demos/analytics/AnalyticsDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { TableAPI, Theme } from "@simple-table/svelte";
  import {
    analyticsDemoConfig,
    analyticsPresets,
    analyticsRows,
  } from "./analytics.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "480px", theme }: { height?: string | number | null; theme?: Theme } = $props();

  let activeId = $state(analyticsPresets[0].id);
  let searchText = $state("");
  let tableRef = $state<{ getAPI: () => TableAPI | null } | null>(null);
  const active = $derived(analyticsPresets.find((p) => p.id === activeId) ?? analyticsPresets[0]);
  const isPivoted = $derived(active.pivot != null);
  const nestedRows = $derived((active.pivot?.rows.length ?? 0) > 1);
  const isDark = $derived(theme === "dark" || theme === "modern-dark");
  const chromeBg = $derived(isDark ? "#0f172a" : "#f8fafc");
  const chromeBorder = $derived(isDark ? "#1e293b" : "#e2e8f0");
  const titleColor = $derived(isDark ? "#f1f5f9" : "#0f172a");
  const mutedColor = $derived(isDark ? "#94a3b8" : "#64748b");
  const chipIdleBg = $derived(isDark ? "#1e293b" : "#e2e8f0");
  const chipIdleColor = $derived(isDark ? "#cbd5e1" : "#334155");
  const inputBg = $derived(isDark ? "#1e293b" : "#fff");
  const inputBorder = $derived(isDark ? "#334155" : "#cbd5e1");
  const inputColor = $derived(isDark ? "#e2e8f0" : "#0f172a");
  const formatHeight = $derived(
    height == null ? "100%" : typeof height === "number" ? `${height}px` : height
  );

  function getRowId({ row }: { row: { id?: unknown } }) {
    return row.id == null ? undefined : String(row.id);
  }
</script>

<div
  style="display: flex; flex-direction: column; width: 100%; height: {formatHeight}; background: {chromeBg}; border: 1px solid {chromeBorder}; border-radius: 8px; overflow: hidden"
>
  <div style="padding: 16px 20px 12px; border-bottom: 1px solid {chromeBorder}; flex-shrink: 0">
    <div style="margin-bottom: 10px">
      <h2
        style="margin: 0; font-size: 18px; font-weight: 650; color: {titleColor}; letter-spacing: -0.02em"
      >
        Revenue Analytics
      </h2>
      <p style="margin: 4px 0 0; font-size: 13px; color: {mutedColor}">
        {active.description} · {analyticsRows.length} fact rows{isPivoted
          ? " → pivoted matrix"
          : ""}
      </p>
    </div>
    <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 10px">
      {#each analyticsPresets as preset}
        <button
          type="button"
          onclick={() => (activeId = preset.id)}
          style="padding: 7px 12px; border-radius: 6px; border: none; cursor: pointer; font-size: 13px; font-weight: 550; background: {preset.id ===
          activeId
            ? '#2563eb'
            : chipIdleBg}; color: {preset.id === activeId ? '#fff' : chipIdleColor}"
        >
          {preset.label}
        </button>
      {/each}
    </div>
    <div style="display: flex; flex-wrap: wrap; gap: 8px; align-items: center">
      <input
        type="search"
        bind:value={searchText}
        placeholder="Quick filter…"
        aria-label="Quick filter"
        style="flex: 1 1 180px; max-width: 280px; padding: 7px 10px; border-radius: 6px; border: 1px solid {inputBorder}; background: {inputBg}; color: {inputColor}; font-size: 13px; outline: none"
      />
      <button
        type="button"
        onclick={() => tableRef?.getAPI()?.exportToCSV()}
        style="padding: 7px 12px; border-radius: 6px; border: 1px solid {inputBorder}; cursor: pointer; font-size: 13px; font-weight: 550; background: {chipIdleBg}; color: {chipIdleColor}"
      >
        Export CSV
      </button>
    </div>
  </div>
  <div
    style="flex: 1; min-height: 0; padding: 12px 20px 20px; display: flex; flex-direction: column"
  >
    <div style="flex: 1; min-height: 0; height: 100%">
      {#key activeId}
        <SimpleTable
          bind:this={tableRef}
          autoExpandColumns={true}
          columnBorders={true}
          columnReordering={true}
          columnResizing={true}
          copyHeadersToClipboard={true}
          defaultHeaders={analyticsDemoConfig.headers}
          editColumns={true}
          enableStickyParents={nestedRows}
          expandAll={nestedRows}
          {getRowId}
          height="100%"
          includeHeadersInCSVExport={true}
          initialSortColumn={isPivoted ? undefined : "sales"}
          initialSortDirection={isPivoted ? undefined : "desc"}
          pivot={active.pivot}
          quickFilter={{ text: searchText, mode: "simple", caseSensitive: false }}
          rows={analyticsDemoConfig.rows}
          selectableCells={true}
          {theme}
          useHoverRowBackground={true}
          useOddEvenRowBackground={true}
        />
      {/key}
    </div>
  </div>
</div>

// packages/examples/angular/src/demos/analytics/analytics-demo.component.ts
import { Component, Input, ViewChild } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { SimpleTableComponent } from "@simple-table/angular";
import type { AngularHeaderObject, PivotConfig, Row, Theme } from "@simple-table/angular";
import {
  analyticsDemoConfig,
  analyticsPresets,
  analyticsRows,
  type AnalyticsPreset,
} from "./analytics.demo-data";
import "@simple-table/angular/styles.css";

@Component({
  selector: "analytics-demo",
  standalone: true,
  imports: [SimpleTableComponent, FormsModule],
  template: `
    <div
      [style.display]="'flex'"
      [style.flexDirection]="'column'"
      [style.width]="'100%'"
      [style.height]="formatHeight"
      [style.background]="chromeBg"
      [style.border]="'1px solid ' + chromeBorder"
      [style.borderRadius]="'8px'"
      [style.overflow]="'hidden'"
    >
      <div
        [style.padding]="'16px 20px 12px'"
        [style.borderBottom]="'1px solid ' + chromeBorder"
        [style.flexShrink]="0"
      >
        <div style="margin-bottom: 10px">
          <h2
            [style.margin]="0"
            [style.fontSize]="'18px'"
            [style.fontWeight]="650"
            [style.color]="titleColor"
            [style.letterSpacing]="'-0.02em'"
          >
            Revenue Analytics
          </h2>
          <p [style.margin]="'4px 0 0'" [style.fontSize]="'13px'" [style.color]="mutedColor">
            {{ activeDescription }} · {{ rowCount }} fact rows{{
              isPivoted ? " → pivoted matrix" : ""
            }}
          </p>
        </div>
        <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 10px">
          @for (preset of presets; track preset.id) {
            <button
              type="button"
              (click)="selectPreset(preset)"
              [style.padding]="'7px 12px'"
              [style.borderRadius]="'6px'"
              [style.border]="'none'"
              [style.cursor]="'pointer'"
              [style.fontSize]="'13px'"
              [style.fontWeight]="550"
              [style.background]="preset.id === activeId ? '#2563eb' : chipIdleBg"
              [style.color]="preset.id === activeId ? '#fff' : chipIdleColor"
            >
              {{ preset.label }}
            </button>
          }
        </div>
        <div style="display: flex; flex-wrap: wrap; gap: 8px; align-items: center">
          <input
            type="search"
            [(ngModel)]="searchText"
            placeholder="Quick filter…"
            aria-label="Quick filter"
            [style.flex]="'1 1 180px'"
            [style.maxWidth]="'280px'"
            [style.padding]="'7px 10px'"
            [style.borderRadius]="'6px'"
            [style.border]="'1px solid ' + inputBorder"
            [style.background]="inputBg"
            [style.color]="inputColor"
            [style.fontSize]="'13px'"
            [style.outline]="'none'"
          />
          <button
            type="button"
            (click)="exportCsv()"
            [style.padding]="'7px 12px'"
            [style.borderRadius]="'6px'"
            [style.border]="'1px solid ' + inputBorder"
            [style.cursor]="'pointer'"
            [style.fontSize]="'13px'"
            [style.fontWeight]="550"
            [style.background]="chipIdleBg"
            [style.color]="chipIdleColor"
          >
            Export CSV
          </button>
        </div>
      </div>
      <div
        style="flex: 1; min-height: 0; padding: 12px 20px 20px; display: flex; flex-direction: column"
      >
        <div style="flex: 1; min-height: 0; height: 100%">
          <simple-table
            #simpleTable
            [autoExpandColumns]="true"
            [columnBorders]="true"
            [columnReordering]="true"
            [columnResizing]="true"
            [rows]="rows"
            [defaultHeaders]="headers"
            [editColumns]="true"
            [expandAll]="nestedRows"
            [getRowId]="getRowId"
            height="100%"
            [initialSortColumn]="isPivoted ? undefined : 'sales'"
            [initialSortDirection]="isPivoted ? undefined : 'desc'"
            [pivot]="pivot"
            [quickFilter]="{ text: searchText, mode: 'simple', caseSensitive: false }"
            [selectableCells]="true"
            [theme]="theme"
          ></simple-table>
        </div>
      </div>
    </div>
  `,
})
export class AnalyticsDemoComponent {
  @ViewChild("simpleTable") tableRef!: SimpleTableComponent;
  @Input() height: string | number | null = "480px";
  @Input() theme?: Theme;

  readonly rows: Row[] = analyticsDemoConfig.rows;
  readonly headers: AngularHeaderObject[] = analyticsDemoConfig.headers;
  readonly presets = analyticsPresets;
  readonly rowCount = analyticsRows.length;
  readonly getRowId = ({ row }: { row: Row }) =>
    row.id == null ? undefined : String(row.id);

  activeId = analyticsPresets[0].id;
  pivot: PivotConfig | null = analyticsPresets[0].pivot;
  nestedRows = (analyticsPresets[0].pivot?.rows.length ?? 0) > 1;
  isPivoted = analyticsPresets[0].pivot != null;
  activeDescription = analyticsPresets[0].description;
  searchText = "";

  get formatHeight(): string {
    if (this.height == null) return "100%";
    if (typeof this.height === "number") return `${this.height}px`;
    return this.height;
  }

  get isDark(): boolean {
    return this.theme === "dark" || this.theme === "modern-dark";
  }

  get chromeBg(): string {
    return this.isDark ? "#0f172a" : "#f8fafc";
  }

  get chromeBorder(): string {
    return this.isDark ? "#1e293b" : "#e2e8f0";
  }

  get titleColor(): string {
    return this.isDark ? "#f1f5f9" : "#0f172a";
  }

  get mutedColor(): string {
    return this.isDark ? "#94a3b8" : "#64748b";
  }

  get chipIdleBg(): string {
    return this.isDark ? "#1e293b" : "#e2e8f0";
  }

  get chipIdleColor(): string {
    return this.isDark ? "#cbd5e1" : "#334155";
  }

  get inputBg(): string {
    return this.isDark ? "#1e293b" : "#fff";
  }

  get inputBorder(): string {
    return this.isDark ? "#334155" : "#cbd5e1";
  }

  get inputColor(): string {
    return this.isDark ? "#e2e8f0" : "#0f172a";
  }

  selectPreset(preset: AnalyticsPreset): void {
    this.activeId = preset.id;
    this.pivot = preset.pivot;
    this.nestedRows = (preset.pivot?.rows.length ?? 0) > 1;
    this.isPivoted = preset.pivot != null;
    this.activeDescription = preset.description;
  }

  exportCsv(): void {
    this.tableRef.getAPI()?.exportToCSV();
  }
}
