// packages/examples/svelte/src/demos/cell-editing/CellEditingDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme, CellChangeProps } from "@simple-table/svelte";
  import { cellEditingConfig } from "./cell-editing.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let data = $state([...cellEditingConfig.rows]);

  function handleCellEdit({ accessor, newValue, row }: CellChangeProps) {
    data = data.map((item) =>
      item.id === row.id ? { ...item, [accessor]: newValue } : item
    );
  }
</script>

<SimpleTable
  columns={cellEditingConfig.headers}
  rows={data}
  {height}
  {theme}
  onCellEdit={handleCellEdit}
/>

// react/cell-editing/src/demos/cell-editing/CellEditingDemo.tsx
import { useState } from "react";
import {SimpleTable} from "@simple-table/react";import type { Theme, CellChangeProps } from "@simple-table/react";
import { cellEditingConfig } from "./cell-editing.demo-data";
import "@simple-table/react/styles.css";

const CellEditingDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [data, setData] = useState([...cellEditingConfig.rows]);

  const handleCellEdit = ({ accessor, newValue, row }: CellChangeProps) => {
    setData((prev) =>
      prev.map((item) =>
        item.id === row.id ? { ...item, [accessor]: newValue } : item
      )
    );
  };

  return (
    <SimpleTable
      columns={cellEditingConfig.headers}
      rows={data}
      height={height}
      theme={theme}
      onCellEdit={handleCellEdit}
    />
  );
};

export default CellEditingDemo;
