// packages/examples/svelte/src/demos/sales/SalesProfitMarginCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import { getThemeColors } from "./sales.demo-data";
  import type { SalesRow } from "./sales.demo-data";

  let { row, theme }: CellRendererProps<SalesRow> = $props();
  const colors = $derived(getThemeColors(theme));

  const pctStyle = $derived.by(() => {
    if (row.profitMargin === "—") return null;
    let color = colors.gray;
    let fontWeight = "normal";
    if (row.profitMargin >= 0.7) {
      color = colors.success.high.color;
      fontWeight = colors.success.high.fontWeight;
    } else if (row.profitMargin >= 0.5) color = colors.success.medium;
    else if (row.profitMargin >= 0.4) color = colors.success.low;
    else if (row.profitMargin >= 0.3) color = colors.info;
    else color = colors.warning;
    const barColor =
      row.profitMargin >= 0.5
        ? colors.progressColors.high
        : row.profitMargin >= 0.3
          ? colors.progressColors.medium
          : colors.progressColors.low;
    return { color, fontWeight, barColor, pct: `${(row.profitMargin * 100).toFixed(1)}%`, w: row.profitMargin * 100 };
  });
</script>

{#if row.profitMargin === "—"}
  —
{:else if pctStyle}
  <div style="display:flex;align-items:center;justify-content:flex-end;">
    <span style="color:{pctStyle.color};font-weight:{pctStyle.fontWeight};">{pctStyle.pct}</span>
    <div style="margin-left:8px;width:48px;">
      <div
        style="background-color:#f5f5f5;height:6px;width:100%;border-radius:100px;overflow:hidden;"
      >
        <div
          style="height:100%;width:{pctStyle.w}%;background-color:{pctStyle.barColor};border-radius:100px;"
        ></div>
      </div>
    </div>
  </div>
{/if}

// angular/sales/src/demos/sales/sales-profit-margin-cell.component.ts
import { Component, Input } from "@angular/core";
import type { Theme } from "@simple-table/angular";
import { getThemeColors } from "./sales.demo-data";
import type { SalesRow } from "./sales.demo-data";

@Component({
  standalone: true,
  selector: "demo-sales-profit-margin",
  template: `
    @if (row.profitMargin === "—") {
      —
    } @else {
      <div style="display:flex;align-items:center;justify-content:flex-end;">
        <span [style.color]="textColor" [style.font-weight]="textWeight">{{ pctLabel }}</span>
        <div style="margin-left:8px;width:48px;">
          <div style="background:#f5f5f5;height:6px;width:100%;border-radius:100px;overflow:hidden;">
            <div
              style="height:100%;border-radius:100px;"
              [style.width.%]="pctWidth"
              [style.background-color]="barColor"
            ></div>
          </div>
        </div>
      </div>
    }
  `,
})
export class SalesProfitMarginCellComponent {
  @Input({ required: true }) row!: SalesRow;
  @Input() theme?: Theme;

  get c(): ReturnType<typeof getThemeColors> {
    return getThemeColors(this.theme);
  }

  get pm(): number {
    return this.row.profitMargin;
  }

  get pctLabel(): string {
    return `${(this.pm * 100).toFixed(1)}%`;
  }

  get pctWidth(): number {
    return this.pm * 100;
  }

  get textColor(): string {
    const c = this.c;
    const m = this.pm;
    if (m >= 0.7) return c.success.high.color;
    if (m >= 0.5) return c.success.medium;
    if (m >= 0.4) return c.success.low;
    if (m >= 0.3) return c.info;
    return c.warning;
  }

  get textWeight(): string {
    return this.pm >= 0.7 ? this.c.success.high.fontWeight : "normal";
  }

  get barColor(): string {
    const pc = this.c.progressColors;
    return this.pm >= 0.5 ? pc.high : this.pm >= 0.3 ? pc.medium : pc.low;
  }
}
