// packages/examples/svelte/src/demos/column-reordering/ColumnReorderingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, HeaderObject } from "@simple-table/svelte";
  import { columnReorderingConfig } from "@simple-table/examples-shared";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let headers: HeaderObject[] = $state([...columnReorderingConfig.headers]);

  function handleColumnOrderChange(newHeaders: HeaderObject[]) {
    headers = newHeaders;
  }
</script>

<SimpleTable
  columnReordering
  defaultHeaders={headers}
  rows={columnReorderingConfig.rows}
  {height}
  {theme}
  onColumnOrderChange={handleColumnOrderChange}
/>

// packages/examples/react/src/demos/column-reordering/ColumnReorderingDemo.tsx
import { useState } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, HeaderObject } from "@simple-table/react";
import { columnReorderingConfig } from "@simple-table/examples-shared";
import "@simple-table/react/styles.css";

const ColumnReorderingDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [headers, setHeaders] = useState<HeaderObject[]>([...columnReorderingConfig.headers]);

  const handleColumnOrderChange = (newHeaders: HeaderObject[]) => {
    setHeaders(newHeaders);
  };

  return (
    <SimpleTable
      columnReordering={columnReorderingConfig.tableProps.columnReordering}
      defaultHeaders={headers}
      rows={columnReorderingConfig.rows}
      height={height}
      theme={theme}
      onColumnOrderChange={handleColumnOrderChange}
    />
  );
};

export default ColumnReorderingDemo;
