// packages/examples/vue/src/demos/nested-headers/NestedHeadersDemo.vue
<template>
  <SimpleTable
    :default-headers="nestedHeadersConfig.headers"
    :rows="nestedHeadersConfig.rows"
    :height="height"
    :theme="theme"
    :column-resizing="true"
  />
</template>

<script setup lang="ts">
import { SimpleTable } from "@simple-table/vue";
import type { Theme } from "@simple-table/vue";
import { nestedHeadersConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>

// packages/examples/svelte/src/demos/nested-headers/NestedHeadersDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { nestedHeadersConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={nestedHeadersConfig.headers}
  rows={nestedHeadersConfig.rows}
  {height}
  {theme}
  columnResizing={true}
/>
