// packages/examples/solid/src/demos/nested-headers/NestedHeadersDemo.tsx
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { nestedHeadersConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

export default function NestedHeadersDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={nestedHeadersConfig.headers}
      rows={nestedHeadersConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      columnResizing
    />
  );
}

// packages/examples/svelte/src/demos/nested-headers/NestedHeadersDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { nestedHeadersConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={nestedHeadersConfig.headers}
  rows={nestedHeadersConfig.rows}
  {height}
  {theme}
  columnResizing={true}
/>
