// packages/examples/svelte/src/demos/soccer/SoccerDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { soccerConfig } from "./soccer.demo-data";
  import type { SoccerPlayer } from "./soccer.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "70dvh", theme }: { height?: string | number; theme?: Theme } = $props();

  const getRowId = ({ row }: GetRowIdParams<SoccerPlayer>) => row.id;
</script>

<SimpleTable
  autoExpandColumns={true}
  columns={soccerConfig.headers}
  rows={soccerConfig.rows}
  getRowId={getRowId}
  {height}
  {theme}
  columnReordering
  columnResizing
  enableColumnEditor
  selectableCells
  initialSortColumn="rating"
  initialSortDirection="desc"
  customTheme={{ headerHeight: 40, rowHeight: 48 }}
/>

// react/soccer/src/demos/soccer/SoccerDemo.tsx
import { SimpleTable } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { soccerConfig } from "./soccer.demo-data";
import "@simple-table/react/styles.css";

const SoccerDemo = ({ height = "70dvh", theme }: { height?: string | number; theme?: Theme }) => {
  return (
    <SimpleTable
      autoExpandColumns
      columns={soccerConfig.headers}
      rows={soccerConfig.rows}
      height={height}
      theme={theme}
      columnReordering
      columnResizing
      enableColumnEditor
      selectableCells
      initialSortColumn="rating"
      initialSortDirection="desc"
      customTheme={{ headerHeight: 40, rowHeight: 48 }}
      getRowId={({ row }) => row.id}
    />
  );
};

export default SoccerDemo;
