// packages/examples/svelte/src/demos/quick-start/QuickStartDemo.svelte
<script lang="ts">
  import { SimpleTable } from "simple-table-svelte";
  import type { Theme } from "simple-table-svelte";
  import { quickStartConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "300px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={quickStartConfig.headers}
  rows={quickStartConfig.rows}
  {height}
  {theme}
  editColumns={quickStartConfig.tableProps.editColumns}
  selectableCells={quickStartConfig.tableProps.selectableCells}
  customTheme={quickStartConfig.tableProps.customTheme}
/>

// packages/examples/react/src/demos/quick-start/QuickStartDemo.tsx
import { SimpleTable } from "simple-table-react";
import type { Theme } from "simple-table-react";
import { quickStartConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

const QuickStartDemo = ({
  height = "300px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={quickStartConfig.headers}
      rows={quickStartConfig.rows}
      height={height}
      theme={theme}
      editColumns={quickStartConfig.tableProps.editColumns}
      selectableCells={quickStartConfig.tableProps.selectableCells}
      customTheme={quickStartConfig.tableProps.customTheme}
    />
  );
};

export default QuickStartDemo;
