// svelte/column-resizing/src/demos/column-resizing/ColumnResizingDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, SvelteColumnDef, GetRowIdParams } from "@simple-table/svelte";
  import { columnResizingHeaders, columnResizingData, COLUMN_RESIZING_STORAGE_KEY } from "./column-resizing.demo-data";
  import type { OceanStaff } from "./column-resizing.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  let headers: SvelteColumnDef<OceanStaff>[] = $state([...columnResizingHeaders]);
  let saveMessage = $state("");

  const getRowId = ({ row }: GetRowIdParams<OceanStaff>) => row.id;

  $effect(() => {
    try {
      const saved = localStorage.getItem(COLUMN_RESIZING_STORAGE_KEY);
      if (saved) {
        const widthMap = JSON.parse(saved);
        headers = columnResizingHeaders.map((h) => ({ ...h, width: widthMap[h.accessor] ?? h.width }));
      }
    } catch { /* ignore */ }
  });

  function handleColumnWidthChange(updatedHeaders: SvelteColumnDef<OceanStaff>[]) {
    try {
      const widthMap: Record<string, unknown> = {};
      for (const h of updatedHeaders) widthMap[h.accessor] = h.width;
      localStorage.setItem(COLUMN_RESIZING_STORAGE_KEY, JSON.stringify(widthMap));
      headers = updatedHeaders;
      saveMessage = "Column widths saved!";
      setTimeout(() => { saveMessage = ""; }, 2000);
    } catch {
      saveMessage = "Failed to save widths";
      setTimeout(() => { saveMessage = ""; }, 2000);
    }
  }
</script>

<div style="position: relative; height: 100%">
  {#if saveMessage}
    <div style="position: absolute; top: 8px; right: 8px; background: #10b981; color: white; padding: 8px 16px; border-radius: 6px; font-size: 14px; font-weight: 500; z-index: 1000; box-shadow: 0 2px 8px rgba(0,0,0,0.15);">
      {saveMessage}
    </div>
  {/if}
  <SimpleTable
    columnResizing={true}
    columns={headers}
    rows={columnResizingData}
    getRowId={getRowId}
    {height}
    {theme}
    onColumnWidthChange={handleColumnWidthChange}
  />
</div>

// solid/column-resizing/src/demos/column-resizing/ColumnResizingDemo.tsx
import { createSignal, onMount, onCleanup } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, SolidColumnDef } from "@simple-table/solid";
import {
  columnResizingHeaders,
  columnResizingData,
  COLUMN_RESIZING_STORAGE_KEY,
  type OceanStaff,
} from "./column-resizing.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnResizingDemo(props: { height?: string | number; theme?: Theme }) {
  const [headers, setHeaders] = createSignal([...columnResizingHeaders]);
  const [saveMessage, setSaveMessage] = createSignal("");

  let messageTimer: ReturnType<typeof setTimeout> | undefined;

  const clearMessageTimer = () => {
    if (messageTimer !== undefined) {
      clearTimeout(messageTimer);
      messageTimer = undefined;
    }
  };

  onMount(() => {
    try {
      const saved = localStorage.getItem(COLUMN_RESIZING_STORAGE_KEY);
      if (saved) {
        const widthMap = JSON.parse(saved) as Record<string, number | string | undefined>;
        setHeaders(
          columnResizingHeaders.map((h) => ({ ...h, width: widthMap[h.accessor] ?? h.width })),
        );
      }
    } catch {
      /* ignore */
    }
  });

  onCleanup(() => {
    clearMessageTimer();
  });

  const handleColumnWidthChange = (updatedHeaders: SolidColumnDef<OceanStaff>[]) => {
    try {
      const widthMap: Record<string, unknown> = {};
      for (const h of updatedHeaders) widthMap[h.accessor] = h.width;
      localStorage.setItem(COLUMN_RESIZING_STORAGE_KEY, JSON.stringify(widthMap));
      setHeaders(updatedHeaders);
      setSaveMessage("Column widths saved!");
      clearMessageTimer();
      messageTimer = setTimeout(() => setSaveMessage(""), 2000);
    } catch {
      setSaveMessage("Failed to save widths");
      clearMessageTimer();
      messageTimer = setTimeout(() => setSaveMessage(""), 2000);
    }
  };

  return (
    <div style={{ position: "relative", height: "100%" }}>
      {saveMessage() && (
        <div
          style={{
            position: "absolute",
            top: "8px",
            right: "8px",
            background: "#10b981",
            color: "white",
            padding: "8px 16px",
            "border-radius": "6px",
            "font-size": "14px",
            "font-weight": "500",
            "z-index": 1000,
            "box-shadow": "0 2px 8px rgba(0,0,0,0.15)",
          }}
        >
          {saveMessage()}
        </div>
      )}
      <SimpleTable
        columnResizing
        columns={headers()}
        getRowId={({ row }) => row.id}
        rows={columnResizingData}
        height={props.height ?? "400px"}
        theme={props.theme}
        onColumnWidthChange={handleColumnWidthChange}
      />
    </div>
  );
}
