// packages/examples/react/src/demos/animations/AnimationsDemo.tsx
import { useState } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, ReactColumnDef } from "@simple-table/react";
import { animationsConfig, type AnimationsCrewMember } from "./animations.demo-data";
import "@simple-table/react/styles.css";

const AnimationsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [headers, setHeaders] = useState(() => [...animationsConfig.headers]);

  const handleColumnOrderChange = (newHeaders: ReactColumnDef<AnimationsCrewMember>[]) => {
    setHeaders(newHeaders);
  };

  return (
    <SimpleTable<AnimationsCrewMember>
      columnReordering={animationsConfig.tableProps.columnReordering}
      columns={headers}
      enableColumnEditor={animationsConfig.tableProps.enableColumnEditor}
      enableColumnEditorInitOpen={animationsConfig.tableProps.enableColumnEditorInitOpen}
      getRowId={({ row }) => row.id}
      rows={animationsConfig.rows}
      height={height}
      theme={theme}
      onColumnOrderChange={handleColumnOrderChange}
    />
  );
};

export default AnimationsDemo;

// solid/animations/src/demos/animations/AnimationsDemo.tsx
import { createSignal } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, SolidColumnDef } from "@simple-table/solid";
import { animationsConfig, type AnimationsCrewMember } from "./animations.demo-data";
import "@simple-table/solid/styles.css";

export default function AnimationsDemo(props: { height?: string | number; theme?: Theme }) {
  const [headers, setHeaders] = createSignal([...animationsConfig.headers]);

  const handleColumnOrderChange = (newHeaders: SolidColumnDef<AnimationsCrewMember>[]) => {
    setHeaders(newHeaders);
  };

  return (
    <SimpleTable
      columnReordering={animationsConfig.tableProps.columnReordering}
      columns={headers()}
      enableColumnEditor={animationsConfig.tableProps.enableColumnEditor}
      enableColumnEditorInitOpen={animationsConfig.tableProps.enableColumnEditorInitOpen}
      getRowId={({ row }) => row.id}
      rows={animationsConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      onColumnOrderChange={handleColumnOrderChange}
    />
  );
}
