// svelte/collapsible-columns/src/demos/collapsible-columns/CollapsibleColumnsDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(collapsibleColumnsConfig.headers)}
  rows={collapsibleColumnsConfig.rows}
  columnResizing={true}
  editColumns={true}
  selectableCells={true}
  columnReordering={true}
  {height}
  {theme}
/>

// react/collapsible-columns/src/demos/collapsible-columns/CollapsibleColumnsDemo.tsx
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { collapsibleColumnsConfig } from "./collapsible-columns.demo-data";
import "@simple-table/react/styles.css";

const CollapsibleColumnsDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(collapsibleColumnsConfig.headers)}
      rows={collapsibleColumnsConfig.rows}
      columnResizing
      editColumns
      selectableCells
      columnReordering
      height={height}
      theme={theme}
    />
  );
};

export default CollapsibleColumnsDemo;
