// react/single-row-children/src/demos/single-row-children/SingleRowChildrenDemo.tsx
import {SimpleTable} from "@simple-table/react";import type { Theme } from "@simple-table/react";
import { singleRowChildrenConfig } from "./single-row-children.demo-data";
import "@simple-table/react/styles.css";

const SingleRowChildrenDemo = ({ height = "400px", theme }: { height?: string | number; theme?: Theme }) => {
  return (
    <SimpleTable
      columns={singleRowChildrenConfig.headers}
      rows={singleRowChildrenConfig.rows}
      columnResizing={singleRowChildrenConfig.tableProps.columnResizing}
      selectableCells={singleRowChildrenConfig.tableProps.selectableCells}
      height={height}
      theme={theme}
      getRowId={({ row }) => row.id}
    />
  );
};

export default SingleRowChildrenDemo;

// packages/examples/svelte/src/demos/single-row-children/SingleRowChildrenDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme, GetRowIdParams } from "@simple-table/svelte";
  import { singleRowChildrenConfig } from "./single-row-children.demo-data";
  import type { StudentRecord } from "./single-row-children.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();

  const getRowId = ({ row }: GetRowIdParams<StudentRecord>) => row.id;
</script>

<SimpleTable
  columns={singleRowChildrenConfig.headers}
  rows={singleRowChildrenConfig.rows}
  getRowId={getRowId}
  columnResizing={singleRowChildrenConfig.tableProps.columnResizing}
  selectableCells={singleRowChildrenConfig.tableProps.selectableCells}
  {height}
  {theme}
/>
