// svelte/cell-clicking/src/demos/cell-clicking/CellClickPriorityCell.svelte
<script lang="ts">
  import type { CellRendererProps } from "@simple-table/svelte";
  import type { ProjectTask } from "./cell-clicking.demo-data";

  let { row }: CellRendererProps<ProjectTask> = $props();
  const p = $derived(String(row.priority));
  const color = $derived(p === "High" ? "#ef4444" : p === "Medium" ? "#f59e0b" : "#10b981");
</script>

<span style="color:{color};font-weight:bold;cursor:pointer;" title="Click to filter by priority">{p}</span>

// angular/cell-clicking/src/demos/cell-clicking/cell-click-priority-cell.component.ts
import { Component, Input } from "@angular/core";
import type { ProjectTask } from "./cell-clicking.demo-data";

@Component({
  standalone: true,
  selector: "demo-cell-click-priority",
  template: `
    <span [style.color]="color" style="font-weight:bold;cursor:pointer;" title="Click to filter by priority">{{ row.priority }}</span>
  `,
})
export class CellClickPriorityCellComponent {
  @Input({ required: true }) row!: ProjectTask;

  get color(): string {
    const p = this.row.priority;
    if (p === "High") return "#ef4444";
    if (p === "Medium") return "#f59e0b";
    return "#10b981";
  }
}
