// svelte/cell-highlighting/src/demos/cell-highlighting/CellHighlightingDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { cellHighlightingConfig } from "./cell-highlighting.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(cellHighlightingConfig.headers)}
  rows={cellHighlightingConfig.rows}
  {height}
  {theme}
  selectableCells={cellHighlightingConfig.tableProps.selectableCells}
  selectableColumns={cellHighlightingConfig.tableProps.selectableColumns}
/>

// solid/cell-highlighting/src/demos/cell-highlighting/CellHighlightingDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { cellHighlightingConfig } from "./cell-highlighting.demo-data";
import "@simple-table/solid/styles.css";

export default function CellHighlightingDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(cellHighlightingConfig.headers)}
      rows={cellHighlightingConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      selectableCells={cellHighlightingConfig.tableProps.selectableCells}
      selectableColumns={cellHighlightingConfig.tableProps.selectableColumns}
    />
  );
}
