// svelte/column-filtering/src/demos/column-filtering/ColumnFilteringDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { columnFilteringConfig } from "./column-filtering.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(columnFilteringConfig.headers)}
  rows={columnFilteringConfig.rows}
  {height}
  {theme}
/>

// solid/column-filtering/src/demos/column-filtering/ColumnFilteringDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { columnFilteringConfig } from "./column-filtering.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnFilteringDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(columnFilteringConfig.headers)}
      rows={columnFilteringConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
