// packages/examples/vue/src/demos/table-height/TableHeightDemo.vue
<template>
  <div>
    <div style="display: flex; gap: 8px; margin-bottom: 12px">
      <button
        v-for="h in heights"
        :key="h"
        @click="selectedHeight = h"
        :style="{
          padding: '6px 12px',
          borderRadius: '4px',
          border: '1px solid #ccc',
          background: selectedHeight === h ? '#3b82f6' : '#f3f4f6',
          color: selectedHeight === h ? '#fff' : '#374151',
          cursor: 'pointer',
          fontSize: '14px',
          fontWeight: '500',
        }"
      >
        {{ h }}
      </button>
    </div>
    <SimpleTable
      :columns="tableHeightConfig.headers"
      :rows="tableHeightConfig.rows"
      :get-row-id="getRowId"
      :height="selectedHeight"
      :theme="theme"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { SimpleTable } from "@simple-table/vue";
import type { Theme, GetRowIdParams } from "@simple-table/vue";
import { tableHeightConfig } from "./table-height.demo-data";
import type { HeightDemoEmployee } from "./table-height.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});

const getRowId = ({ row }: GetRowIdParams<HeightDemoEmployee>) => row.id;

const heights = ["200px", "300px", "400px"];
const selectedHeight = ref("400px");
</script>

// angular/table-height/src/demos/table-height/table-height-demo.component.ts
import { Component, Input } from "@angular/core";
import {SimpleTableComponent} from "@simple-table/angular";import type { AngularColumnDef, GetRowIdParams, Theme } from "@simple-table/angular";
import { tableHeightConfig } from "./table-height.demo-data";
import "@simple-table/angular/styles.css";
import type { HeightDemoEmployee } from "./table-height.demo-data";

@Component({
  selector: "table-height-demo",
  standalone: true,
  imports: [SimpleTableComponent],
  template: `
    <div>
      <div style="display: flex; gap: 8px; margin-bottom: 12px">
        @for (h of heights; track h) {
          <button
            (click)="selectedHeight = h"
            [style.padding]="'6px 12px'"
            [style.borderRadius]="'4px'"
            [style.border]="'1px solid #ccc'"
            [style.background]="selectedHeight === h ? '#3b82f6' : '#f3f4f6'"
            [style.color]="selectedHeight === h ? '#fff' : '#374151'"
            [style.cursor]="'pointer'"
            [style.fontSize]="'14px'"
            [style.fontWeight]="'500'"
          >
            {{ h }}
          </button>
        }
      </div>
      <simple-table
      [getRowId]="getRowId"
        [rows]="rows"
        [columns]="headers"
        [height]="selectedHeight"
        [theme]="theme"
      ></simple-table>
    </div>
  `,
})
export class TableHeightDemoComponent {
  @Input() height: string | number = "400px";
  @Input() theme?: Theme;

  readonly rows: HeightDemoEmployee[] = tableHeightConfig.rows;
  readonly headers: AngularColumnDef<HeightDemoEmployee>[] = tableHeightConfig.headers;
  readonly heights = ["200px", "300px", "400px"];
  selectedHeight = "400px";

  getRowId = ({ row }: GetRowIdParams<HeightDemoEmployee>) => row.id;
}
