// vue/column-filtering/src/demos/column-filtering/ColumnFilteringDemo.vue
<template>
  <SimpleTable
    :columns="columnFilteringConfig.headers"
    :rows="columnFilteringConfig.rows"
    :height="height"
    :theme="theme"
  />
</template>

<script setup lang="ts">
import {SimpleTable} from "@simple-table/vue";import type { Theme } from "@simple-table/vue";
import { columnFilteringConfig } from "./column-filtering.demo-data";
import "@simple-table/vue/styles.css";

withDefaults(defineProps<{ height?: string | number; theme?: Theme }>(), {
  height: "400px",
});
</script>

// packages/examples/svelte/src/demos/column-filtering/ColumnFilteringDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnFilteringConfig } from "./column-filtering.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={columnFilteringConfig.headers}
  rows={columnFilteringConfig.rows}
  {height}
  {theme}
/>
