// packages/examples/solid/src/demos/column-filtering/ColumnFilteringDemo.tsx
import {SimpleTable} from "@simple-table/solid";import type { Theme } from "@simple-table/solid";
import { columnFilteringConfig } from "./column-filtering.demo-data";
import "@simple-table/solid/styles.css";

export default function ColumnFilteringDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      columns={columnFilteringConfig.headers}
      rows={columnFilteringConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}

// packages/examples/svelte/src/demos/column-filtering/ColumnFilteringDemo.svelte
<script lang="ts">
  import {SimpleTable} from "@simple-table/svelte";  import type { Theme } from "@simple-table/svelte";
  import { columnFilteringConfig } from "./column-filtering.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  columns={columnFilteringConfig.headers}
  rows={columnFilteringConfig.rows}
  {height}
  {theme}
/>
