// packages/examples/svelte/src/demos/row-height/RowHeightDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { rowHeightConfig } from "./row-height.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(rowHeightConfig.headers)}
  rows={rowHeightConfig.rows}
  {height}
  {theme}
  customTheme={rowHeightConfig.tableProps.customTheme}
/>

// react/row-height/src/demos/row-height/RowHeightDemo.tsx
import { SimpleTable, defaultHeadersFromCore } from "@simple-table/react";
import type { Theme } from "@simple-table/react";
import { rowHeightConfig } from "./row-height.demo-data";
import "@simple-table/react/styles.css";

const RowHeightDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(rowHeightConfig.headers)}
      rows={rowHeightConfig.rows}
      height={height}
      theme={theme}
      customTheme={rowHeightConfig.tableProps.customTheme}
    />
  );
};

export default RowHeightDemo;
