// svelte/themes/src/demos/themes/ThemesDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { themesConfig, AVAILABLE_THEMES } from "./themes.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
  let selectedTheme: Theme = $state(theme ?? "light");
</script>

<div>
  <div style="display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 12px">
    {#each AVAILABLE_THEMES as t}
      <button
        onclick={() => (selectedTheme = t.value)}
        style="padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; border: {selectedTheme === t.value ? '2px solid #3b82f6' : '1px solid #d1d5db'}; background: {selectedTheme === t.value ? '#eff6ff' : '#fff'}; color: {selectedTheme === t.value ? '#1d4ed8' : '#374151'}; font-weight: {selectedTheme === t.value ? 600 : 400}"
      >
        {t.label}
      </button>
    {/each}
  </div>
  <SimpleTable
    defaultHeaders={defaultHeadersFromCore(themesConfig.headers)}
    rows={themesConfig.rows}
    {height}
    theme={selectedTheme}
  />
</div>

// packages/examples/solid/src/demos/themes/ThemesDemo.tsx
import { createSignal, For } from "solid-js";
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { themesConfig, AVAILABLE_THEMES } from "./themes.demo-data";
import "@simple-table/solid/styles.css";

export default function ThemesDemo(props: { height?: string | number; theme?: Theme }) {
  const [selectedTheme, setSelectedTheme] = createSignal<Theme>(props.theme ?? "light");

  return (
    <div>
      <div style={{ display: "flex", "flex-wrap": "wrap", gap: "8px", "margin-bottom": "12px" }}>
        <For each={AVAILABLE_THEMES}>
          {(t) => (
            <button
              onClick={() => setSelectedTheme(t.value)}
              style={{
                padding: "6px 14px",
                "border-radius": "6px",
                border: selectedTheme() === t.value ? "2px solid #3b82f6" : "1px solid #d1d5db",
                background: selectedTheme() === t.value ? "#eff6ff" : "#fff",
                color: selectedTheme() === t.value ? "#1d4ed8" : "#374151",
                "font-weight": selectedTheme() === t.value ? 600 : 400,
                cursor: "pointer",
                "font-size": "13px",
              }}
            >
              {t.label}
            </button>
          )}
        </For>
      </div>
      <SimpleTable
        defaultHeaders={defaultHeadersFromCore(themesConfig.headers)}
        rows={themesConfig.rows}
        height={props.height ?? "400px"}
        theme={selectedTheme()}
      />
    </div>
  );
}
