// solid/aggregate-functions/src/demos/aggregate-functions/AggregateFunctionsDemo.tsx
import {SimpleTable, defaultHeadersFromCore} from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
import "@simple-table/solid/styles.css";

export default function AggregateFunctionsDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  return (
    <SimpleTable
      defaultHeaders={defaultHeadersFromCore(aggregateFunctionsConfig.headers)}
      rows={aggregateFunctionsConfig.rows}
      rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
      columnResizing
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}

// svelte/aggregate-functions/src/demos/aggregate-functions/AggregateFunctionsDemo.svelte
<script lang="ts">
  import {SimpleTable, defaultHeadersFromCore} from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { aggregateFunctionsConfig } from "./aggregate-functions.demo-data";
  import "@simple-table/svelte/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={defaultHeadersFromCore(aggregateFunctionsConfig.headers)}
  rows={aggregateFunctionsConfig.rows}
  rowGrouping={aggregateFunctionsConfig.tableProps.rowGrouping}
  columnResizing={true}
  {height}
  {theme}
/>
