// packages/examples/react/src/demos/external-sort/ExternalSortDemo.tsx
import { useState, useMemo } from "react";
import { SimpleTable } from "@simple-table/react";
import type { Theme, SortColumn } from "@simple-table/react";
import { externalSortConfig, type SortableEmployee } from "./external-sort.demo-data";
import "@simple-table/react/styles.css";

const ExternalSortDemo = ({
  height = "400px",
  theme,
}: {
  height?: string | number;
  theme?: Theme;
}) => {
  const [sortConfig, setSortConfig] = useState<SortColumn | null>(null);

  const sortedData = useMemo(() => {
    if (!sortConfig) return externalSortConfig.rows;
    const sorted = [...externalSortConfig.rows].sort((a, b) => {
      const key = sortConfig.key.accessor as keyof SortableEmployee;
      const aVal = a[key];
      const bVal = b[key];
      if (aVal === bVal) return 0;
      const cmp =
        sortConfig.key.type === "number"
          ? (aVal as number) - (bVal as number)
          : String(aVal).localeCompare(String(bVal));
      return sortConfig.direction === "asc" ? cmp : -cmp;
    });
    return sorted;
  }, [sortConfig]);

  return (
    <SimpleTable<SortableEmployee>
      columns={externalSortConfig.headers}
      rows={sortedData}
      onSortChange={setSortConfig}
      externalSortHandling
      columnResizing
      height={height}
      theme={theme}
      getRowId={({ row }) => row.id}
    />
  );
};

export default ExternalSortDemo;

// solid/external-sort/src/demos/external-sort/ExternalSortDemo.tsx
import { createSignal, createMemo } from "solid-js";
import { SimpleTable } from "@simple-table/solid";
import type { Theme, SortColumn } from "@simple-table/solid";
import { externalSortConfig, type SortableEmployee } from "./external-sort.demo-data";
import "@simple-table/solid/styles.css";

export default function ExternalSortDemo(props: {
  height?: string | number;
  theme?: Theme;
}) {
  const [sortConfig, setSortConfig] = createSignal<SortColumn | null>(null);

  const sortedData = createMemo(() => {
    const sort = sortConfig();
    if (!sort) return externalSortConfig.rows;
    return [...externalSortConfig.rows].sort((a, b) => {
      const key = sort.key.accessor as keyof SortableEmployee;
      const aVal = a[key];
      const bVal = b[key];
      if (aVal === bVal) return 0;
      const cmp =
        sort.key.type === "number"
          ? (aVal as number) - (bVal as number)
          : String(aVal).localeCompare(String(bVal));
      return sort.direction === "asc" ? cmp : -cmp;
    });
  });

  return (
    <SimpleTable
      columns={externalSortConfig.headers}
      getRowId={({ row }) => row.id}
      rows={sortedData()}
      onSortChange={setSortConfig}
      externalSortHandling
      columnResizing
      height={props.height ?? "400px"}
      theme={props.theme}
    />
  );
}
