// packages/examples/solid/src/demos/quick-filter/QuickFilterDemo.tsx
import { SimpleTable } from "@simple-table/solid";
import type { Theme } from "@simple-table/solid";
import { quickFilterConfig } from "@simple-table/examples-shared";
import "simple-table-core/styles.css";

export default function QuickFilterDemo(props: { height?: string | number; theme?: Theme }) {
  return (
    <SimpleTable
      defaultHeaders={quickFilterConfig.headers}
      rows={quickFilterConfig.rows}
      height={props.height ?? "400px"}
      theme={props.theme}
      quickFilter={quickFilterConfig.tableProps.quickFilter}
    />
  );
}

// packages/examples/svelte/src/demos/quick-filter/QuickFilterDemo.svelte
<script lang="ts">
  import { SimpleTable } from "@simple-table/svelte";
  import type { Theme } from "@simple-table/svelte";
  import { quickFilterConfig } from "@simple-table/examples-shared";
  import "simple-table-core/styles.css";

  let { height = "400px", theme }: { height?: string | number; theme?: Theme } = $props();
</script>

<SimpleTable
  defaultHeaders={quickFilterConfig.headers}
  rows={quickFilterConfig.rows}
  {height}
  {theme}
  quickFilter={quickFilterConfig.tableProps.quickFilter}
/>
